### ISSUE TITLE
File system store

### ISSUE THREAD

**Issue by fourpixels** [expressjs/session#139]
Hi there,
As I'm developing on windows and currently using mysql (can't switch to mongo), I would love to have file system storage support. I found one here:

https://github.com/tnantoka/connect-fs

It's not regularly updated, but seems pretty simple as logic and I guess it's working :) It implements almost all the functions (except `touch`), so I think it's safe to add it as a compatible storage :)

**Comment by JoeWagner** [comment]
Three and a half years since the last commit to `connect-fs`, thats really impressive if its still working!

There is a somewhat newer option available here
https://github.com/valery-barysok/session-file-store

I haven't used either of those solutions, so I don't have any comment as to if they should be included in the list of stores.
@dougwilson do you have any thoughts on requirements for being in the list of [compatible stores](https://github.com/expressjs/session#compatible-session-stores)?

**Comment by fourpixels** [comment]
I won't argue for that - it just seems pretty straightforward. They are basically doing the very same thing.. valery-barysok's solutions seems nice too, but it's a bit over complicated in my opinion (those attempts and stuff).

Anyway - will try to use them both these days and figure out any drawbacks, but just wanted to drop a line, as people just coming by will be thinking "oh, no, there is no file system store!" :)

Cheers!

**Comment by dougwilson** [comment]
@JoeWagner the bar is pretty low: just that it works with this module in some kind of fashion (where you can pass something from that module as the `store` option).
