### ISSUE TITLE
Documentation for session store implementations

### ISSUE THREAD

**Issue by joepie91** [expressjs/session#147]
The documentation for implementing session stores appears rather incomplete - it only really lists the expected function signatures, and suffers from some other problems:

* Some implementations are missing some of these methods. It's unclear what the consequences of this are, or why one would want to omit these methods.
* The responsibilities of `express-session` vs. those of the session stores are unclear - for example, which of the two is responsible for expiring sessions?
* Some implementations have *extra* methods, where it isn't clear whether those are actually used by `express-session` or whether they are convenience functions available for manual use - eg. [`.all`](https://github.com/expressjs/session/blob/master/session/memory.js#L56-L70). The documentation says "including but not limited to", but does not expand on what the full list *is*.
* The intended functionality of `touch` - ie. specifically what behaviour it is supposed to implement - is completely unclear. Should it be storing an updated version of the cookie object? Should it just reset a TTL? Why is a `session` object passed to it, when a `touch` implementation of any kind usually does not take any input data?
* The documentation refers to the Redis store as a reference implementation, but the Redis store doesn't even implement all the methods listed in the documentation - `.touch`, for example, is completely missing.

I feel the documentation needs some serious work. I've been trying to get a reliable session store implementation done for the past two days, and I'm still not confident that it is ready for production use, as the documentation doesn't clearly indicate what is expected from a session store.

Aside from the request to clarify the documentation, I'd at least appreciate some informal answers to the specific questions above, so that I can get a production-ready store implementation running.

**Comment by dougwilson** [comment]
Yes, I 100% agree the docs are lacking, though haven't had the time to sit down and write them out after inheriting this module (because writing those would almost be it's own little project to do), and I'm pretty sure some people brought it up earlier as well. They'll be there if I ever get the time to write them, though of course always open if someone wants to contribute them :)

> The responsibilities of express-session vs. those of the session stores are unclear - for example, which of the two is responsible for expiring sessions?

It's the store's responsibility currently. `connect-redis` I believe has a good example of this in action.

> The documentation says "including but not limited to", but does not expand on what the full list is.

Because people can call methods directly on your store object, you can add all kinds of things for users. As far as this module, we only require the three listed ones and will call `.touch` if it's there; this module doesn't call any other methods besides those for (plus the `EventEmitter` interface methods).

> Should it be storing an updated version of the cookie object? Should it just reset a TTL? Why is a session object passed to it, when a touch implementation of any kind usually does not take any input data?

It depends on how your store functions. I can help if I know more about your store. We send youo as much data as possible to help your store do whatever it needs to keep the session alive (since it's the store's responsibility for expiring sessions).

**Comment by Magnitus-** [comment]
If it helps, I noted some behaviour for express-session (when sessions get deleted outside of express-session) that is pertinent to session-store implementors in the 'Additional Notes on TimeToLive and express-session' and 'FlagDeletion and Cleanup methods' section for the documentation on my session store:

https://www.npmjs.com/package/express-session-mongodb

**Comment by dougwilson** [comment]
So I finally got around to updating it. Please open new issues or PRs if there is something specific wrong with the new docs :)
