### ISSUE TITLE
Default session expiration behaviour

### ISSUE THREAD

**Issue by t0lkman** [expressjs/session#151]
I cannot find anywhere what the default behavior for:

1) For how long sessions are available in mongo (i use mongo-connect)
2) when user open and close the browser, does it create new session (record)?

**Comment by JoeWagner** [comment]
1) is defined by the store you choose, and settings you pass to it.  For connect-mongo, [the docs](https://github.com/kcbanner/connect-mongo#session-expiration) explain it well
  2) The browser will handle cookies differently depending on the [cookie options](https://github.com/expressjs/session#cookie-options) you choose.  Note that just because a cookie expires it doesn't mean that the session record will be removed, depending on the store you are using.

**Comment by dougwilson** [comment]
Hey @t0lkman let us know if you have any more questions (unless they are about the mongo driver). I see you created a duplicate issue over at the mongo store here: https://github.com/kcbanner/connect-mongo/issues/169

**Comment by t0lkman** [comment]
Thank you!  Joe explained it pretty well
