### ISSUE TITLE
Close browser session seems not be cleared

### ISSUE THREAD

**Issue by zwb-ict** [expressjs/session#166]
I use node + express + express-session + passport + passport-local + passport-local-mongoose. My intention is: when I close browser, the browser's cookie is cleared automatic. But It seems not work.

    var app = express()
        .engine('hb.html', handlebars.engine)
        .set('view engine', 'hb.html')
        .set('port', process.env.PORT || 3000)
        .use(morgan('dev'))
        .use(favicon(path.join(__dirname, '/public/favicon.ico')))
        .use(bodyParser.json())
        .use(bodyParser.urlencoded({ extended: false }))
        .use(require('express-session')({
            key: 'nwitter.Sid',
            store: new mongoSessionStore({ url: configDB.url }),
            resave: false,
            saveUninitialized: false,
            secret: credentials.cookieSecret,
            cookie: {
                secure: false,
                maxAge: null
            }
        }))
        .use(function(req, res, next) {
            var inspect = require('util');
            console.log("req.session: " + inspect(req.session));
            next();
        })
        .use(passport.initialize())
        .use(passport.session())

I check the express-session's README, when set **maxAge null**, it means:
> By default cookie.maxAge is null, meaning no "expires" parameter is set so the cookie becomes a browser-session cookie. When the user closes the browser the cookie (and session) will be removed.

But when I reboot browser, and visit my website, I found the session still exist.(Notice the **console.log()** in my code).

>req.session: { cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true,
     secure: false },
  passport: { user: 'example@railstutorial.org' } }

**Comment by dougwilson** [comment]
Unfortunately without access to your browser it's not possible to debug, since it's a browser issue, rather than a server issue. My suggestion is to clear all the cookies in your browser so you are working from a clean state.

Then restart the browser (this is really tricky if you are using a Mac, as closing all the windows does not actually close the browser; consult your OS manual for more information on closing apps). Then open your browser's cookie management system to verify the cookie does not exist (consult the manual for your relevant browser). Then visit the web site so the cookie is set. Then go back to your browser's cookie management system to see what it says about the cookie, like if it is a session-length cookie or not. Then close and open your browser, open the cookie management system and check if the cookie is still there.

If you can paste the outgoing response headers your server is sending (should have the `Set-Cookie` header in there), we can verify if there is anything wrong with the server, at least.

**Comment by zwb-ict** [comment]
You’re right! The reason is I didn’t close my browser (mac) , after I close chrome correctly, it works OK.

I’m very sorry to bother you, and thank you for your help! I’ll be careful.

-- 
zwb.ict
Sent with Airmail

在 2015年5月29日 下午10:59:24, Douglas Christopher Wilson (notifications@github.com) 写到:

Closed #166.

**Comment by dougwilson** [comment]
No problem, man!
