### ISSUE TITLE
Sharing session between different client applications

### ISSUE THREAD

**Issue by aybmab** [expressjs/session#221]
We have two different client applications accessing the same server. We would like to make it so that if a user signs in through one application, if they access the other (on the same browser), they would automatically be signed in. 

Is this possible?

**Comment by gabeio** [comment]
If both applications are connected to the same session store (database) and are sharing the same keys this is exactly what this module was made for.

**Comment by aybmab** [comment]
Thanks for the response!

I think I might have asked under the wrong module...I also probably wasn't clear enough. I have an express app that I'm using as a REST API server. If I happen to mount a client app to this server as a static file, it can make the API calls (like login, get x, update y, etc.) without any problems. If I create a different client application hosted on a different server and try to make API calls to my express server, the request fails. I think this is a CORS issue and not a sessions one. Sorry!

**Comment by aybmab** [comment]
So looking deeper into it, for some reason, POST requests from the client app sitting on a different server generates new sessionIds....loosing track of the user after they signed in. 

Any ideas what may be happening there?

**Comment by gabeio** [comment]
So you have two servers are they running different nodejs scripts or identical scripts? Are they both using the same session storage & the same session options? Also are you running behind an HTTP/S reverse proxy (these if using the wrong session/express settings can cause sessions to be constantly created because of http/s mismatch & reverse proxy trust)?

**Comment by aybmab** [comment]
Are they running different nodejs scripts or identical scripts?
One is an express app. The other is a simple server that just renders static files (the web client app).

Are they both using the same session storage & the same session options?
Only one has sessions...we're trying to let that server handle sessions. Should we not do this?

Also are you running behind an HTTP/S reverse proxy (these if using the wrong session/express settings this can cause sessions to be constantly created because of http/s mismatch & reverse proxy trust)?
I don't think we're running behind a reverse proxy...How would we know?

Thanks for the help!

**Comment by gabeio** [comment]
> The other is a simple server that just renders static files (the web client app). 
Only one has sessions...we're trying to let that server handle sessions. Should we not do this?

that sounds normal...

> I don't think we're running behind a reverse proxy...How would we know?

if you are running Nginx, haproxy or are behind cloudflare (or something similar)

**Comment by aybmab** [comment]
Ahh - then we are not running behind a reverse proxy.

**Comment by gabeio** [comment]
:disappointed: I am out of ideas

**Comment by aybmab** [comment]
:(

Generally speaking, which session options would cause sessions to be recreated?

**Comment by gabeio** [comment]
well there's a few that I can think of: `cookie: { secure: true }` and you are serving http would cause the cookie to only be sent back to the server using https but since the server is http it won't be or more likely just to be ignored because the original connection was not https.

If I remember correctly when the database and session are not talking it can but usually you will get errors about trying to save the session because `req.session` will not exists and therefore `req.session.<something>` will be a "bigger" error... 

Finally if you happen to be doing a `req.session.id = <something>` you may be overwriting the session's id and some weird things can happen.

**Comment by Josh-a-e** [comment]
We've got a solution which I believe is similar to the one you are describing @aybmab - common causes of cookie recreation we found were a) internal requests, where no cookies were sent from one machine to another, thus the machine receiving the requests goes "ah, you don't have a session id, let me create one for you", b) the domain being different, e.g. requests being made to elb-12345.something.aws.amazon.com rather than example.com, c) different cookie secrets being used for the encryption / decryption of cookies: typically the node express cookie will just act as if no cookies are available (and create a new one) if decryption fails

**Comment by dougwilson** [comment]
Hi!

99% of the time, a session is re-createdh because the `Cookie` header in the request that reached Express was either missing (thus this module thinks there is no session and creates a new one) or somehow it's a stale cookie.

Diagnosing this is probably going to have to lean on you, who can reproduce the issue with your setup (as it's likely a setup/configuration issue), but I can help you with tips! My first tip would be to completely delete all cookies from the web browser you are testing with to see if that solves the issue.

If that does not help, I suggest using a tool external to the web browser like Wireshark or Fiddler to inspect the request your web browser is making to your Express server. Verify that there is a `Cookie` header in the request and it contains the session ID you expect.

If that looks right, then it's possible it's getting lost somewhere in the Node.js application. I suggest connecting a debugger to your Node.js server and setting a breakpoint within Express's source code, probably here: https://github.com/strongloop/express/blob/4.13.3/lib/application.js#L158 At that point, inspect `req.headers.cookie` to see if it contains the content you expect. If it does, simply start stepping through the code to see what is happening and if it gets lost, overwritten, or if some condition is hit somewhere that prevents the session from being loaded.
