### ISSUE TITLE
Session generation questions

### ISSUE THREAD

**Issue by parky128** [expressjs/session#254]
I have just read this [article](https://www.airpair.com/express/posts/expressjs-and-passportjs-sessions-deep-dive#optimize-expressjs-sessions) about when sessions are created by session-express.

I'm just thinking about a typical scenario where someone follows a link to a page in an application they need to be logged into. So lets say they do this after a few hours of using it last and their cookie has now expired.

Am I correct in thinking the following occurs in Express?:

User follows link and a new session gets created by express-session and stored e.g. mongodb, whatever, when they attempt to access the page.
Express logic determines they are not logged in (check for presence of some custom user property on the request object for example) and redirects to the login page.
Q - Does a new session get created here?
User logs in and they get redirected to the root page (e.g index) of main application
Q - Does a new session get created here also?

By default, so without setting a maxAge for the cookie config options, does this mean a new session gets generated per request made?

I'm thinking more about how I would detect if the user is logged in and redirect them to a login page. From what I understand, express-session will check for the presence of a cookie (e.g. connect.sid), and if none generates and saves a new one to the store. Is there an option to handle the cookie not being present as part of the express-session options to then hook into and perform a simple redirect?

**Comment by dougwilson** [comment]
Hi!

> User follows link and a new session gets created by express-session and stored e.g. mongodb, whatever, when they attempt to access the page.
>  Express logic determines they are not logged in (check for presence of some custom user property on the request object for example) and redirects to the login page.
>  Q - Does a new session get created here?

So by default, yes, when a request comes in without a session ID or one that is not valid, then a new session is created and saved to the data store on that request.

>  User logs in and they get redirected to the root page (e.g index) of main application
>  Q - Does a new session get created here also?

No, because there will already be a cookie from the first request that created the session.

> Is there an option to handle the cookie not being present as part of the express-session options to then hook into and perform a simple redirect?

Not really, you need to add a property to `req.session` that indicates if the user is logged in. Then, every request, just check for that and if it's not there, redirect. This isn't any overhead, because you obviously have to have something in your session to know that a user is logged in, so check for that not to be there and redirect is simple enough.

I hope this helps!
