### ISSUE TITLE
how to change maxAge?

### ISSUE THREAD

**Issue by artofspeed** [expressjs/session#275]
Given a req.session object, how do u change its maxAge? In the following example, I try to change maxAge to 1 week. However, `req.session.touch();` doesn't seem to apply this change.

```
req.session.cookie.maxAge = 7*24*60*60*1000; // make session last 1 week
req.session.touch();
```

**Comment by gabeio** [comment]
`req.session.touch`:
> Updates the `.maxAge` property. Typically this is not necessary to call, as the session middleware does this for you.

req.session.touch resets the maxAge to the default session maxAge that you have given in the config.

only use one or the other of those two lines you showed there.

**Comment by blueror815** [comment]
Hi 
I am using express-session for my project
But I can not retrieve session value, because after saving session, it is destroyed automatically.
I am not sure why this happens.
Could you please help me?
Please review following code.
`-------app.js------`
`var express       =   require('express');`
`var session       =   require('express-session');`
`var path          =   require('path');`
`var favicon       =   require('serve-favicon');`
`var logger        =   require('morgan');`
`var cookieParser  =   require('cookie-parser');`
`var bodyParser    =   require('body-parser');`
`var mongoose      =   require('mongoose');`
`var cors          =   require('cors');`
`var log           =   require('loglevel');`

`require('rootpath')();`
`var routes =  require('config/router');'
`var app = express();`

`app.use(session({ secret: 'SessionSecret' }));`
`app.use(cors());`
`app.options('/api/', cors());`
`routes.setup(app);`
`-----------------------------------------------`

`------------------router.js----------------`
`require('rootpath')();`
`var api_auth_ctrl        =   require('app/controller/api/v1/auth.controller');`

`module.exports.setup = function(app) {`
     `app.post('/api/v1/auth/login',       api_auth_ctrl.login);`
     `app.get('/api/v1/auth/info',       api_auth_ctrl.userInfo)`
`}`
`-----------------------------------------------`

`--------------------auth.js-------------------`
`exports.login = function(req, res) {`
   `req.session.email = req.body.email;`
   `.........`
   `res.json({`
        `type: "success"`
    `});`
`};`
`exports.userInfo = function(req, res) {`
   `var logged_in_user = req.session.email;`
   `.........`
   `res.json({`
        `user: user`
    `});`
`};`

**Comment by gabeio** [comment]
@blueror815 Please open a separate issue.
