### ISSUE TITLE
I want to callback function when session.cookie.maxAge is done

### ISSUE THREAD

**Issue by linejine** [expressjs/session#290]
I want to callback function when session.cookie.maxAge is done.
but, i don't find event that session.cookie.maxAge is done.
what should i do?

for example, i set cookie maxAge 10seconds.
after 10seconds, i want to delete my database.
what should i do?

**Comment by gabeio** [comment]
> after 10seconds, i want to delete my database.

for clarification you want to delete it from your database or you want to delete a whole database?

**Comment by linejine** [comment]
Not  whole database, i want to delete some record in database table.
For example, after maxAge, I want to delete login information.

**Comment by gabeio** [comment]
So something different from the session, correct?

**Comment by linejine** [comment]
In my case, i want to check login and logout information that visit my homepage.
So, i save the information in the database.
And i encountered some difficult situation.
If visitor didn't click logout button, visitor logout automatically by using cookie.maxAge.
If visitor logout automatically using cookie.maxAge, how can i insert logout information in the database?

**Comment by gabeio** [comment]
So the easiest thing here is to use a database the supports expiring inserts like redis, the redis session module supports the expiration i'm not sure if they support adjusting the maxAge to adjust the expiration.

Alternatively I can think of two ways to cleanup the sessions in the database:
 - add the login time into the session and then have something like a crontab which runs at specific times and runs a script that goes through all of the sessions that are in the database look at their maxAge and deletes the doc/row if the maxAge is > the oldestPossible maxAge at that moment. (this is really inefficient)
 - add a timer which auto deletes the session from the database on maxAge
  - this does not work with adjusting the maxAge or you will have to figure out how to save the timeouts and be able to adjust them which ends up being yet another database

honestly I highly suggest redis.

sidenote: 10 seconds is a very short maxAge I hope you realize that it's entirely possible for some users to be logged out the second they log in because they do not realize the have to click something at least every 10 seconds... sessions are usually best to be done with longer timeouts like: 1 hour, 1 day, 1 month...
