### ISSUE TITLE
Prevent Session.touch() on certain routes

### ISSUE THREAD

**Issue by ranode** [expressjs/session#291]
We have one route that the client keeps polling for updates. Even if the user is inactive, there is frequent interaction with the server on this route. This means that the session is never timed out. Is there a way to prevent this route from not updating the session expiry?

**Comment by gabeio** [comment]
It would help to know your session's configurations for example do you have [rolling](https://github.com/expressjs/session#rolling) set to true?

**Comment by blueror815** [comment]
Hi 
I am using express-session for my project
But I can not retrieve session value, because after saving session, it is destroyed automatically.
I am not sure why this happens.
Could you please help me?
Please review following code.
`-------app.js------`
`var express       =   require('express');`
`var session       =   require('express-session');`
`var path          =   require('path');`
`var favicon       =   require('serve-favicon');`
`var logger        =   require('morgan');`
`var cookieParser  =   require('cookie-parser');`
`var bodyParser    =   require('body-parser');`
`var mongoose      =   require('mongoose');`
`var cors          =   require('cors');`
`var log           =   require('loglevel');`

`require('rootpath')();`
`var routes =  require('config/router');'
`var app = express();`

`app.use(session({ secret: 'SessionSecret' }));`
`app.use(cors());`
`app.options('/api/', cors());`
`routes.setup(app);`
`-----------------------------------------------`

`------------------router.js----------------`
`require('rootpath')();`
`var api_auth_ctrl        =   require('app/controller/api/v1/auth.controller');`

`module.exports.setup = function(app) {`
     `app.post('/api/v1/auth/login',       api_auth_ctrl.login);`
     `app.get('/api/v1/auth/info',       api_auth_ctrl.userInfo)`
`}`
`-----------------------------------------------`

`--------------------auth.js-------------------`
`exports.login = function(req, res) {`
   `req.session.email = req.body.email;`
   `.........`
   `res.json({`
        `type: "success"`
    `});`
`};`
`exports.userInfo = function(req, res) {`
   `var logged_in_user = req.session.email;`
   `.........`
   `res.json({`
        `user: user`
    `});`
`};`

**Comment by gabeio** [comment]
@blueror815 Please open a separate issue.

**Comment by dougwilson** [comment]
I'm going to close this issue since there wasn't enough information and a question to collect some more information went unanswered.
