### ISSUE TITLE
Share a session between the same user on multiple browsers

### ISSUE THREAD

**Issue by rightaway** [expressjs/session#304]

**Comment by fvargas** [comment]
The problem with reusing the session id is that you make it impossible for the server to revoke just a single login session.

To illustrate, suppose you're signed in to your Dropbox account on three computers, your phone, and your tablet. If each of these devices were to share the same session id (or auhtorization token), and you wanted to revoke authorization for just your phone because it was stolen, you would have to do so for all your devices because they all share the same authorization token. That wouldn't be very convenient for you as a user.

Therefore, you may want to look into a different solution.

**Comment by rightaway** [comment]
In such cases it would be fine to revoke the authorization token for all devices, as it's not such a big deal for them to log in again in rare cases where they need to revoke an authorization token for one device. The revocation form would then say something like "End current login session" or "End session on all devices" instead of "End session on device A".

**Comment by gireeshpunathil** [comment]
@rightaway - is this still a problem for you?

Can you pls elaborate a bit on your use case? what is the real need for accessing a webapp from multiple devices under the same session?
