### ISSUE TITLE
saveUninitialized doesn't work

### ISSUE THREAD

**Issue by brendonparker** [expressjs/session#314]
Sessions are always saved, even when `saveUninitialized` is set to `false`. 

I've done a little bit of investigation, and I think I have identified the issue. Looks like it is in lines [420 - 429](https://github.com/expressjs/session/blob/master/index.js#L423-425). When it hashes the "original session" it does so session without the `id` being set on it. So when it hashes it again at the end of the request the `shouldSave` returns `true` because the session now has the `id` set.

If this is indeed the problem, one approach might be replacing `store.createSession(req, sess);` with `sess = store.createSession(req, sess);`

**Comment by dougwilson** [comment]
Hi @brendonparker, the lines you highlighted are for a session that was loaded from the store, not a newly-created session. The `saveUninitialized` only applies to new sessions that were not originally in the store.

If you are looking for an option to not resaved loaded, but not modified sessions, perhaps you are looking to use the `resave` option?

**Comment by brendonparker** [comment]
Hrm. I'll look some more, but I'm hitting that block when opening a new tab incognito, so I'd assume there is no existing session in the store.

**Comment by dougwilson** [comment]
Gotcha. I mean, we have tests and they are passing just fine. Perhaps you can provide all of the following information so we can look into it?

1. The version of Node.js.
2. The version of this module.
3. Full code that we can copy and paste and run as-is to reproduce the issue. Should have as little dependencies as possible.
4. Complete steps for us to reproduce the issue.

It's possible that you have a cookie in your web browser, because even incognito still stores cookies :) Perhaps try clearing all cookies from the browser or even try restarting your computer to be sure Chrome is recycled. The code path you highlighted can only be triggered from a cookie bring sent from the browser to load an already-existing session from the store.

**Comment by dougwilson** [comment]
> When it hashes the "original session" it does so session without the id being set on it. So when it hashes it again at the end of the request the shouldSave returns true because the session now has the id set.

Can you link to the part in the code that is setting the `id` property after that hash is taken?

**Comment by brendonparker** [comment]
The issue I'm experiencing is with brand new sessions getting created
before a user logs in. Specifically with an AWS health check url generating
a bunch of unnecessary sessions. I'll put together a sample here shortly
(Just stepped out for lunch). Thanks for the prompt replies.

**Comment by brendonparker** [comment]
In trying to setup a sample that demonstrates the issue, I found that the `connect-ensure-login` middleware I am using was adding a "returnTo" url in the session, which caused the session to be saved. It has a flag to disable that feature, and that prevented the sessions from being prematurely created in my sample, but I am still having the problem in my larger, non-sample app, so must be something similar happening there. I'll continue to investigate.

**Comment by brendonparker** [comment]
I figured it out... Somehow was using an older version of passportjs (0.2.2). Updated to 0.3.2, which fixed [this issue](https://github.com/jaredhanson/passport/issues/279). The old version was adding an empty passport object to the session, which caused the dirty check to fail, and this created the session. Sorry for the false alarm and thanks for your help. 

The moral of the story, for other who experience this problem in the future, is to make sure that you don't have some middleware that is adding things to the req.session object unnecessarily.

**Comment by dougwilson** [comment]
Hi @brendonparker, thanks for the updates! A user contributed a note about PassportJS in our `saveUninitialized` documentation (https://github.com/expressjs/session#saveuninitialized) to help others, and it sounds like PassportJS has addressed it :) If you like, please feel free to update that section to add in that it's fixed in version xxx or higher, that would be appreciated!

**Comment by brendonparker** [comment]
Yes, I did read that. Not sure how I got the older version of passport, could have swore I installed the latest. Will do.

**Comment by dougwilson** [comment]
Hi @brendonparker, I'm sorry, I didn't mean to imply you didn't read it :) I was just trying to word it that a PR to add the new version information would be awesome, which you've done in PR #316 :O

**Comment by brendonparker** [comment]
I knew that you weren't implying that, no offense taken. Just simply stating that I read that and didn't click.
 :+1:

**Comment by meetDeveloper** [comment]
@brendonparker  Sir, Can I chat with you, I have few doubts about sessions that are troubling me.
