### ISSUE TITLE
Two connect.sid cookies with different values?

### ISSUE THREAD

**Issue by cainvommars** [expressjs/session#318]
express: 4.13.1
express-session 1.7.2
connect-memcached 0.1.0

Sometimes I have two connect.sid cookies with different values in the clients browsers. This causes trouble finding the correct session again. I'm done debugging through my application and I'm totally clueless.

Is there any lead what could cause that?

It's happening sometimes, not reproducible, but constantly. It might be only on chrome...

**Comment by gabeio** [comment]
How are you seeing these two values? (In one request?) because sid should only ever be one value because the browser's cookies are key value pairs I don't believe you can have two different values for the same key in one request if the browser is correctly following the standard

**Comment by dougwilson** [comment]
Hi! The only reason a browser would have two cookies with the same name is because they have at least one other non-value attribute that differs. If you have access to a Chrome browser where you have two cookies, I'm sure there is some way in Chrome to see the attributes for the cookies. You can see which ones differ (for example, maybe it is the path, domain, secure, httpOnly, or something).

You can then use the "cookie" option in this middleware to set the attribute values you want explicitly instead of letting the browser choose,which can lead to the issue you see.

I hope this helps!

**Comment by cainvommars** [comment]
Thanks for the quick responses! This is whats shown in the chromes network tab for the request I'm doing. It's a xhr request, all other values seem idential.
The initial, non xhr, request only has one connect.sid. Also other xhr requests have two connect.sid entries. When I'm opening the exact same page in a privacy window there is only one connect.sid entry visible.
<img width="924" alt="bildschirmfoto 2016-06-04 um 22 29 57" src="https://cloud.githubusercontent.com/assets/185672/15801922/431b72f0-2aa4-11e6-846e-8a0137ddfb91.png">

**Comment by dougwilson** [comment]
Hi @cainvommars, I looked up the help for how to use the Chrome developers tool, and I'm not sure what screen you are showing there, but it doesn't show any of the cookie's attributes. You can find them by going to your site, opening the developer tools (F12), clicking on the Resources tab, then expand Cookies and choose the domain those requests are for.

There is a column for each attribute and you'll be able to tell which ones are different.

**Comment by cainvommars** [comment]
@dougwilson Sorry for the confusion. I could have made the screenshots bigger. Its the network tab from dev tools and I'm only looking at a xhr request right now:
<img width="1244" alt="network" src="https://cloud.githubusercontent.com/assets/185672/15804997/fc74fd12-2b1b-11e6-85bc-ef1d30f7cbf1.png">

The tab you are describing looks like this:
<img width="1246" alt="application" src="https://cloud.githubusercontent.com/assets/185672/15804999/0a3a99de-2b1c-11e6-9c93-a0e0d5339255.png">

I wonder shouldn't the values of at least one connect.sid entry match?
(seems like chrome beta got a design update, i have the same error on regular chromes..)

**Comment by dougwilson** [comment]
Hi @cainvommars, hm, I really don't know what the issue is here, and that's confounded by me just not knowing what to tell you what to look at in the Chrome browser. If you delete all your cookies in Chrome (through the setting menu, I presume) can you re-create the issue? If so, would you be able to provide me with complete server code and complete instructions I can follow that reproduces the issue so I can take a stab at debugging it?

**Comment by cainvommars** [comment]
hey @dougwilson. I can reproduce the issue when deleting cookies sometimes... So its _not_ a constants behavior. But one thing is for sure, its cookie related, restarting the browser didn't change anything. Whats confusing is that we only saw this in chrome. That makes it even more fun to debug...
I sadly can't send you the code in any form. What I'd love to do, if you would be up for this, is setting up a call and I'll guide you through my setup and show you the interesting parts. Where you located?

**Comment by dougwilson** [comment]
Hi @cainvommars, I would not mind doing that, but the biggest issue is that I just never have the time to help :( For example, tonight I thought I would be able to update some modules like this, but no, some advisory was published to `nsp` and now I have to publish a whole bunch of updates :)

I am in the U.S. Eastern time zone.

Maybe there is another option? Perhaps if you can clear out all the cookies to where you don't have the issue, then using something like Fiddler to record your entire session until you end up with the issue. If you can send me the Fiddler trace, that may help a lot, since if there is something from this module, it would have to be visible in that trace.

**Comment by cainvommars** [comment]
@dougwilson can i reach out to you via mail? I'm gonna write down what I have right now and what I've done to cover up the issue.

**Comment by dougwilson** [comment]
Hi @cainvommars, sure, my email is on my GitHub profile page and in the `package.json` here :)
