### ISSUE TITLE
cookie.maxAge confusing documentation

### ISSUE THREAD

**Issue by nwoltman** [expressjs/session#320]
The [(first) documentation](https://github.com/expressjs/session#maxage) for the `maxAge` cookie option says "Specifies the number (in seconds)", which is confusing because in this module the `maxAge` option must be provided as a number in milliseconds. I know the current description was copied from the [cookie](https://github.com/jshttp/cookie) module, but perhaps there could be some sort of clarification added to indicate that the number should be specified in milliseconds?

**Comment by dougwilson** [comment]
Thanks, @nwoltman, looks like an oversight! :)

**Comment by dougwilson** [comment]
Personally, it bugs me that the `cookie` module takes seconds and not milliseconds, since most things are milliseconds-based in JS. I get that I just inherited the module and it does match that of the actual attribute, but if there is a better reason to justify a major bump of that module, I'll surely change it.

For here, a fix to the documentation is in order, I think.

**Comment by dougwilson** [comment]
In general, the docs for `maxAge`/`expires` is actually a little more wrong than just the wrong units :) Fixing it up now, thanks for the heads-up!

**Comment by nwoltman** [comment]
No problem :+1:  Thanks for the fix :)
