### ISSUE TITLE
Sessions collection is too big

### ISSUE THREAD

**Issue by zilions** [expressjs/session#325]
I installed `connect-mongo` a few days ago now to store my `express-session`s in my DB. Today I checked my sessions collection and found out that there were more than 200,000 documents in there! I tried deleting my collection and waiting 60 seconds, and there were already 200 documents in there.

Why are documents being resaved even though I have `resave` set to `false`? It seems as if documents are being saved endlessly...

Here is my current configuration:

```
app.use(session({
    secret: config.secret,
    resave: false,
    saveUninitialized: false,
    unset: 'destroy',
    store: new MongoStore({
        mongooseConnection: mongoose.connection,
        touchAfter: 3600, //Restore once every hour
        autoRemove: 'interval',
        autoRemoveInterval: 60 //Remove after one hour
    })
}));
```

At most I would only have around 3 users using my app at the moment.

I contacted `connect-mongo` and they stated that it would have to be an issue with `express-session`.

**Comment by dougwilson** [comment]
Hi @zillions, I'm sure there is some reason, but without access to your server, I really have no way to answer the question. Do you know what kind of requests are creating the sessions? Are they web search crawlers? Bots? Something else? Can you confirm what version of this module you have installed is to alidate that your settings like `resave` are actually performing their function? Is there anything you can provide us to reproduce the issue at all?

**Comment by zilions** [comment]
Hey @dougwilson. I'm using the most recent version of both `connect-mongo` and `express-session` available on NPM. Literally the only setup I have is the code I posted in my original question.

I'm using Compose.io to host my MongoDB (formally known as MongoHQ).

Here is how I connect to it:

```
var ca = [fs.readFileSync(process.env.PWD + "/certs/db-cert.crt")];
mongoose.connect(config.database, {
	mongos: {
		ssl: true,
		sslValidate: true,
		sslCA:ca
	}
});
```

Does that help at all?

**Comment by romeboards** [comment]
@zilions also experiencing this issue (or a similar one) with `resave: true`, if that's useful

**Comment by dougwilson** [comment]
Hi @zilions @romeboards, the extra information does not really help. I really don't know anything about the MongoDB so don't have any idea what the indexes means. In addition, you haven't actually provided any information for how I am supposed to reproduce the issue. Can you provide all the following information?

1. Version of Node.js you are using.
2. Version of this module and store (*you already provided this, just listing for completion*)
3. Full server code that I can copy-and-paste and reproduce the issue. No, just showing your setup for this module is not useful, because with what you provided, no sessions are ever created. I'm assuming you have some logic somewhere that is actually adding data to the session, and understanding what that is is critical in diagnosing this issue.
4. Full instructions on how to reproduce the issue, with a description of what I should see when it is reproducing. Provide instructions either with how to access the app, what calls to make to the app, or another complete script that triggers the issue against your app.

**Comment by romeboards** [comment]
@dougwilson some basic info:

Using `express-session@1.9.3` with Node.js `0.10.46` on a heroku build.

Full serverside code (and the rest of the repo for that matter) can be found [here](https://github.com/JustFixNYC/tenants/blob/master/config/express.js)

What is interesting is that this issue does not seem to exist on my local version (development environment with a local instance of MongoDB) and only on my testing server (heroku using mLab Mongo instance)

Session documents (individual items in the collection) grow rampantly. Some _uninformed_ guesses were bots or something that is causing a session to be created with every request to the server (including static assets...)

**Comment by dougwilson** [comment]
Hi @romeboards, ah, that makes sense. Please see the documentation for the `saveUninitialized` https://github.com/expressjs/session#saveuninitialized, specifically the following note:

> Note if you are using Session in conjunction with PassportJS, Passport will add an empty Passport object to the session for use after a user is authenticated, which will be treated as a modification to the session, causing it to be saved. This has been fixed in PassportJS 0.3.0

Can you try upgrading your version of PassportJS?

**Comment by dougwilson** [comment]
@romeboards , you also need ton use `saveUninitialized: false`, not `saveUninitialized: true` in your code, otherwise everything that hits your server, event assets, will keep creating a new session. If you are using `true`, then what you are experiencing is expected...

**Comment by dougwilson** [comment]
Also @romeboards, can you try upgrading to the latest version of this module? It's hard to help if you are using probably a known-buggy version.

**Comment by romeboards** [comment]
@dougwilson yeah, the passport issue was what I thought at first. I had found [this shim](https://github.com/wesleytodd/express-session-passport-cleanup) which was said to alleviate the issue (at different, passport-less session started being created) but the new sessions being created en masse did not seem to stop. 

Just set `saveUninitialized: false` and will leave overnight to see if that changes anything, otherwise will work to update the dependencies and test again.

**Comment by romeboards** [comment]
Change seems to work... using both `saveUninitialized: false` and [express-session-passport-cleanup](https://github.com/wesleytodd/express-session-passport-cleanup). Obviously this should just be temporary, need to make the appropriate upgrades all around :~)

Hopefully this is of some use on your end, @zilions

**Comment by zilions** [comment]
Hmmm, still unable to get any progress here. I have `saveUninitialized ` set to `false`. I'm not using Passport, instead I'm using my own scripts such as `jwt` (JSON Web Tokens). Although that has nothing to do with sessions.

**Comment by JoeWagner** [comment]
@zilions From your first post you mention that you've got 200 documents after 60 seconds.  Thats about 3 requests a second. That seems like quite a few for only 3 users. Do you log all requests?  If you are getting that many requests, then somewhere in your code you are probably touching the session for each request even though you aren't intending to use it.  Based on previous issues I've seen, this is potentially happening in the `jwt` script you mention.  But, I have no way to know that without grepping around your code.
If you aren't getting 3 requests/second, then something other than `express-session` is likely the culprit.  
Either way, I wouldn't think the indexes you have set on the collection have anything to do with the issue.

**Comment by shaurabhbharti** [comment]
I am facing similar issue. I have following settings. 
Nodejs : 0.10.35
Redis : 2.6
saveUninitialized: false
resave: false

My website is deployed on an openshift gear. Every 2 seconds a new session is saved in redis store. This is, as my best guess, due to HAProxy continuous pinging the server, every 2 seconds.
