### ISSUE TITLE
readme formatting confusing

### ISSUE THREAD

**Issue by greaber** [expressjs/session#326]
Hey, I just noticed that I had misconfigured this library by putting the "secure" option in the main options section instead of under "cookie".  I think the reason is that the way the readme is formatted, it is easy to make this mistake.  I wonder if a lot of other people have made it.  If I hadn't been looking at my headers I wouldn't know that I was not sending secure cookies.  Could also possibly have the library print a warning about cookie options in the non-cookie session if it finds them there.

**Comment by dougwilson** [comment]
Hi @greaber, what are your suggestions to improve the README? We are using HTML/Markdown structure to map out the object property levels without a ton of redundancy. We've been using this format around these organizations for years without any comment (though that doesn't mean people just haven't been saying anything).

> Could also possibly have the library print a warning about cookie options in the non-cookie session if it finds them there.

No.

**Comment by greaber** [comment]
The problem is you are distinguishing between the two levels by whether it is five hashes deep or six hashes deep, and the Markdown formatting to distinguish such deep levels is very subtle, just a slightly different shade of gray.  I think either use less deep levels or Maybe use bullets or a list or something for the cookie options.

**Comment by dougwilson** [comment]
> I think either use less deep levels 

We are already uses the lowest level we can

> Maybe use bullets or a list or something for the cookie options.

We tried that in the past, but it becomes really really hard to have large amounts of documentation and example insides each section.

**Comment by greaber** [comment]
You could also split it into multiple pages.

**Comment by dougwilson** [comment]
The npmjs.com website only allows us to publish 1 page, and we really value people being able to read the documentation on that web site, with GitHub being the secondary source. This is mainly because almost all people come to GitHub and just read whatever they see, which is usually the `master` branch, which is very likely to have changes that are not actually published, meaning when they install the module, they do not actually have the code the documentation is written for.

**Comment by greaber** [comment]
I think a lot of projects have primary docs off of the Github project page.  They could be on a Github.io page or on expressjs.com.  The Github project page could link to that so that people get the docs for the stable version.  And the npmjs page could just be the front page to that site, with off-site links to the sub-pages.

There are obviously tradeoffs with all these approaches, and everything takes work.  I just wanted to point out that the hierarchy is quite hard to discern given the way things are done now.  It led me to misconfigure things in a way that silently made my server less secure.  When I think about it, it is obvious that `secure` should be a cookie option, but it is still an easy mistake to make.

Curious why you don't like printing warnings, by the way.  It seems like if someone has `secure` or `maxAge` in the main options section, it can't hurt to warn about it.  Anyway, I will close the issue.  Maybe it is actually extremely few people who made my mistake; it just struck me that it might not be.

**Comment by dougwilson** [comment]
> Curious why you don't like printing warnings

The main reason is that 1) there is no precedent for this in JavaScript itself; you can set all kind of properties on things that ignore them and nothing warns about anything 2) how are we even supposed to perform warnings? `console.warn` seems OK, except almost always that ends up somewhere no one reads (believe me--we have that in there for the `MemoryStore` and still get complaints that wouldn't have happened if they saw the warning), it's hard to redirect those calls to go to a logging mechanism, and it's just not pluggable.

The other thing I was just thinking about when looking at the secure section, is that in that very section, we have a code example, showing you were the `secure` option actually goes. Was that not enough to help you understand where to put the option? At the top of the `cookie` session, we show what the object looks like as well (in the sub context). I'm sure there are additional ways we can help, and I understand that since you filed those issues, none of those things actually helped you understand where the option should have gone, so I just don't know what to change...
