### ISSUE TITLE
explanation of when secure cookies are sent confusing

### ISSUE THREAD

**Issue by greaber** [expressjs/session#327]
I think the logic for deciding whether to send a cookie at all could be more clearly explained.  Is the following correct?

1. If "secure" is falsy or "auto", a cookie will be sent.
2. Otherwise, if the socket is secure, a cookie will be sent.
3. Otherwise, if both of the following conditions are true, a cookie will be sent.
   - trust proxy is set in Express or the "proxy" option is truthy
   - the X-Forwarded-Proto header is present with a value of "https"
4. Otherwise, no cookie will be sent.

**Comment by dougwilson** [comment]
Not completely accurate, no. In particular the first bullet point of number 3 glosses over a lot of details that determine if it will get sent or not, mainly because the "trust proxy" setting is not just "set in Express", as it's not simply a Boolean, but can (and should) be used to setup trust and depending on if the trust chain is fulfilled helps determine if it is sent _on top of_ knowing that it is going over a security connection, as determined by some other mechanisms.

**Comment by dougwilson** [comment]
In general, writing documentation is _hard_, and even _harder_ for coders, and even _header_ for those who just know how it works and just can't sit in the shoes of the others who are learning.

I suggest that really, the documentation is what it is, already written by the people would would react to these issues. If you have suggestions, please absolutely feel free to make pull requests, as otherwise, we just don't understand what changes we need to make to improve the clarity of the documentation in your eyes :)

**Comment by greaber** [comment]
Believe me, I understand that writing documentation is hard!
