### ISSUE TITLE
Race condition between session.touch and session.save

### ISSUE THREAD

**Issue by guoxing** [expressjs/session#340]
https://github.com/expressjs/session/commit/50cdae238a3806df75302f73ed280e361f13eebb

The above commit introduced in 1.14.0 moves `req.session.touch()` to onHeaders. This causes a race condition, where save is called before session is touched, which further makes session expiration time not updated.

I downgraded to 1.13.0 fixed the issue.

Not sure if you guys are able to reproduce. Let me know if you need more info. Thanks.

**Comment by dougwilson** [comment]
How is it a race condition? `.touch()` is not an async activity, all it does is set a property: https://github.com/expressjs/session/blob/master/session/session.js#L59 The `onHeaders` function should always be called before anything contained in `.write` or `.end` overrides. Can you provide the following?

1. The version of Node.js you are using.
2. Complete code that reproduces the issue such that I can copy and paste it and run it without modification.
3. Instructions on exactly how I can reproduce the issue, explain what happens when the issue occurs and explain what you are expecting to happen.

Thanks for the report!

**Comment by dougwilson** [comment]
> The onHeaders function should always be called before anything contained in .write or .end overrides

Nevermind, we don't called `_implicitHeader`, so I don't think you need to provide any further information for me to investigate.

**Comment by binarydud** [comment]
we just noticed similar behavior. The `end` function that saves the session back to the store is called before the headers are sent. So the req.session.touch in `onHeaders` is called after saving the session to the store. So the cookie as a new expires on it, but the session store does not have a new expires value.

**Comment by dougwilson** [comment]
Yep. I was just working on the fix the other day, but have been busy today, so haven't uploaded the fix. It has been completed, though, just need to upload it :)

**Comment by binarydud** [comment]
awesome, thanks.

**Comment by gordomium** [comment]
＋1
