### ISSUE TITLE
Question: Ability to switch the session id for a user

### ISSUE THREAD

**Issue by reggi** [expressjs/session#359]
Hey @dougwilson, quick question for you. I couldn't find this in the docs.

Let's say I have 5 sessions in Redis. A user hits the server and another one is created so I now have a total of 6. I'm interested in switching or setting the current session for the user to one of the previous 5 sessions.

I'm looking for a function like `req.session.set(sid)`. Does something like this exist? Is this possible?

**Comment by dougwilson** [comment]
I would use an association table, only store the base user session identifier in the express-session table and the rest of the data in a different table. You can easily make a session store that does this all transparently.

You cannot simply modify the session id from this module because even though that sounds trivial, it is not. For one, your set-cookie can easily be overwritten back to the first value. It also means that you loose the ability for a user to "sign out from all other sessions" in your UI if all sessions have the same cookie value.

**Comment by dougwilson** [comment]
Hi @reggi I hope it's OK that I close this issue, since I think I answered your question, and there hasn't been any followup :)
