### ISSUE TITLE
Array value is flushed

### ISSUE THREAD

**Issue by tokidoki11** [expressjs/session#366]
so I set a value of array with 

``` js
req.session.value = new Array[];
error.forEach(function(currValue, index, array) {
                            req.session.formError[currValue.param] = {
                                msg: currValue.msg,
                                value: currValue.value
                            }
                        });
console.log(req.session)
res.redirect('/register');
```

the console log display

```
 Session {
   cookie:
    { path: '/',
      _expires: null,
      originalMaxAge: null,
      httpOnly: true },
   formError:
    { message: 'Please recheck your input',
      username:
       { msg: 'Username must only contain numbers or letters and cannot be numbers only',
         value: 'asdasdc' },
      email: { msg: 'Invalid email format', value: 'seecsa@casc' },
      agree: { msg: 'Invalid value', value: '1' } }
 }
```

And in 

``` js
app.get('/register',function(req,res,next)
{
console.log(req.session)
})
```

It displays

```
 Session {
   cookie:
    { path: '/',
      _expires: null,
      originalMaxAge: null,
      httpOnly: true },
   formError: []
 }
```

I manage to fix this by making the formError as JSON

**Comment by dougwilson** [comment]
Hi @tokidoki11 I tried to replicate your issue, but was unable to. We would love to dig into your issue, but there is not enough information provided for us to do so. Can you please provide us with all the following information?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Full, complete source code for an app we can run to reproduce your issue. We need the complete app we can simply copy and paste and run.
4. Describe the steps we need to perform on your app in order to reproduce the problem. Please include a description of what we'll see when the issue occurs.

Thanks!

**Comment by dougwilson** [comment]
Hi @tokidoki11 I'm going to close this issue since I haven't heard back.
