### ISSUE TITLE
req.session.cookie, why not req.sessionCookie?

### ISSUE THREAD

**Issue by caub** [expressjs/session#385]
there are req.sessionID, req.session, and req.sessionStore too, cookie is in req.session.cookie, but it's a special property so it's always messy to serialize/deserialize the session with this special property that is treated differently. I don't think it should have been nested

**Comment by dougwilson** [comment]
Hi @caub the reason that the `cookie` is inside the session object is because it does need to be stored. This is why it is given to the stores to store :) This is to work-around the limitation of how web browsers manage cookies. Once a cookie is set, all the server ever gets back is the name & value of the cookie, but in order to update the value, we need to emit another `Set-Cookie` header that contains all the same attributes like `path`, `domain`, etc from when the cookie was first set, and we don't know what they are unless it was saved to the store.

**Comment by caub** [comment]
Thanks Doug, yes it must be stored, but I was thinking to let the choice on how to store session (without cookie) + cookie. But it's fine with cookie in session, as long as you organize how you store things in session, to serialize it efficiently.

Could you have a look at: https://github.com/jdesboeufs/connect-mongo/pull/246 please, I think it's important
