### ISSUE TITLE
do i need secure: true with nginx?

### ISSUE THREAD

**Issue by artofspeed** [expressjs/session#387]
I have node.js app behind nginx. NginX receive traffic in HTTPS, and redirect it to node.js via HTTP. So nodejs will receive traffic in HTTP.

In this case, do i need to set `secure: true`? Thanks!

**Comment by gabeio** [comment]
Yes, because the cookies have a boolean declaring that they are only for the secure website and as such if express/sessions thinks it should only be running http not https then the https cookies are dropped for security.

**Comment by artofspeed** [comment]
thank you @gabeio , then in this set up, do i need to set `proxy: true` as well?

**Comment by gabeio** [comment]
not if your express has the `'trust proxy'` setting already set if not then yes you should but it's preferable to use the global trust proxy so that the rest of the app also has the correct ip address (instead of 127.0.0.1 as the ip 😄 ). And for better security it's better to use the amount of hops so if you only are running 1 reverse proxy in front then `app.set('trust proxy', 1)` or if you are running also behind cloudflare or similar you should then use 2. there are more details over [here](http://expressjs.com/en/guide/behind-proxies.html)
