### ISSUE TITLE
Provide newly created session as an argument for regenerate callback

### ISSUE THREAD

**Issue by urugator** [expressjs/session#407]
The session regeneration is not happening in-place (which is not clear from documentation), but it's done by reassigning the `session` prop on `req` object.
In order to access regenerated session, user either has to always pass request object together with session object or he has to use `session.req.session` (weird and probably not part of a public API).
  
```javascript
// somewhere outside of middleware, without an access to request
this.session.regenerate(error => {
  if (error) {
    return reject(error);
  }      
  this.session.userId = user.id; // OLD SESSION !!! won't work
  this.session.req.session.userId = user.id // works but wtf...    
  return resolve();
});
```
I think it would make sense to make new session object accessible via callback args:
```javascript
// somewhere outside of middleware, without an access to request
this.session.regenerate((error, session) => {
  if (error) {
    return reject(error);
  }      
  this.session = session; // update session
  this.session.userId = user.id // store something    
  return resolve();
});
```
I also think it better indicates that the "old" session is obsolete...

**Comment by gabeio** [comment]
I don't understand how you could be accessing a session from outside any route scope thusly not having and request access since the session is only found by a request. But yes when you regenerate a session the point is that the session has a new id and everything inside it is back to the way it was when you initialized it, yes nothing inside it is copied. But you can easily make a copy of the session prior to calling regenerate and then copying in what you need:
```js
this.oldSession = this.session; // assuming this.session has the session data prior to regeneration
this.session.regenerate(error => {
  if (error) {
    return reject(error);
  } else {
    // from this point on we should have a blank new session
    // to access old session data use this.oldSession
    // depending on where user.id is being supplied from this should still work or you might need to change it to the following line:
    this.session.userId = this.oldSession.user.id; // OLD SESSION !!! won't work
    // instead of this
    this.session.userId = user.id; // OLD SESSION !!! won't work
    this.session.req.session.userId = user.id // works but wtf...    
    return resolve();
  }
});
```

as for the `this.session.req.session.` I have no idea 😄

**Comment by urugator** [comment]
> I don't understand how you could be accessing a session from outside any route scope

The object using the session is naturally created somewhere in middleware invocation, so passing request is possible, but it doesn't make sense to introduce such dependency. The object depends on session, it doesn't (and shoudn't) require the whole request object.

> But yes when you regenerate a session the point is that the session has a new id

Except it isn't. The original `this.session` object is untouched by regeneration. To get the (regenerated) session with the new ID, you have to obtain a new session object reference from request object. 

>  make a copy of the session prior to calling regenerate 

I think you've misunderstood... I don't need to access the original session, I need the refreshed one,
(btw  creating a copy like `this.oldSession = this.session;` woud not work, it's not a copy, but still the same object reference)

**Comment by gabeio** [comment]
> (btw creating a copy like this.oldSession = this.session; would not work, it's not a copy, but still the same object reference)

when the regeneration occurs it is a pointer to the old session so if you were saving it else where excluding your outside routing case it does work but since that is not relevant to this issue the issue is moot.

> I think you've misunderstood... I don't need to access the original session, I need the refreshed one

Sorry, yes I did not realize what you were having trouble with.

Going back to `this.session.req.session.userId` it seems that the `session.req` is a cyclical pointer to the original request which pulled up the session and in this case where your new session will be placed take a look at [this](https://github.com/expressjs/session/blob/master/session/session.js#L123) and in normal situations would be in the correct place but since your `this.session` is actually only a pointer to the original session it's not going to be. So since I have nothing to test this with I can only guess that doing something along the lines of:

```js
// somewhere outside of middleware, without an access to request
this.session.regenerate(error => {
  if (error) {
    return reject(error);
  }
  this.session = this.session.req.session;
  // do the rest here
  return resolve();
});
```

would be your solution.

**Comment by urugator** [comment]
> So since I have nothing to test this with I can only guess that doing something along the lines of:

Yes, I have already mentioned this solution, but it seems more like a workaround. I just think it would make sense to provide the session in callback. 
You know if you execute a method on an instance you would expect that the method either changes the object itself, or returns something.
If you look at your first comment, it seems you were tricked as well and assumed, that `this.session` inside the callback is the new regenerated session. Since the new regenerated session is not returned, I think this (wrong) assumption is quite natural.

**Comment by gabeio** [comment]
@dougwilson what do you think? I don't see any huge issue with this since it only requires [1 non-breaking edit](https://github.com/gabeio/session/commit/7d7ec9b022a37ee0e6aafa52b39b98a314bf10e1).

**Comment by dougwilson** [comment]
The only thing I would be curious about is if this would automatically work with all the session stores we have listed in our README, since it's possible one of those may have redefined the `.regenerate` method. In addition, I think that the idea behind this issue is flawed in general: `req.session` is an object that is tightly coupled with `req` (which is why it stores it internally) and using it indirectly can result is really weird action-at-a-distance behaviors. Always accessing as `req.session` is the only supported method for using sessions; saving them to another variable is unsupported.

**Comment by urugator** [comment]
Even though I have read the README, I have to admin I really missed the part:
 
> instance will be initialized at req.session

my apologies for that (I was punished already, it took me some time to find the problem), however maybe the example which follows: 

```javascript
req.session.regenerate(function(err) {
  // will have a new session here
})
```
could be a little bit more specific about `here`? You know the thing is you call regenerate on session, but the updated object is not a session, but a request object... if I would call something like `req.regenerateSession()` it would make sense I think... 

> req.session is an object that is tightly coupled with req

I just wonder if the old session object can still be considered "consistent" and usable after the regeneration. It seems that the req object (while still tightly coupled) is no longer relevant to the old session...?

> Always accessing as req.session is the only supported method for using sessions saving them to another variable is unsupported.

I think that mentioning this in documentation could help some stupid people like me. I would dare to claim that inablity to pass an object alone is not ususal and maybe it contradicst with some OOP principes (just some feelings...)?       

Disclaimer: I don't seek "satisfaction", I am just sharing some thoughts ... feel free to not reply and keep this closed ... I respect and appreciate your work and contribution... Happy new year :)
