### ISSUE TITLE
200k session records on db.

### ISSUE THREAD

**Issue by bonesoul** [expressjs/session#413]
I'm using sessions for a fairly active site with sessions set to 1 weeks expire. And last time i checked,i had a total of 200k session entries on my db.

is this all normal or i'm missing something?

**Comment by dougwilson** [comment]
I guess it's normal, but there just isn't enough information to know. Are those sessions all active, expired, something else? Any additional information you can provide.

**Comment by bonesoul** [comment]
they are all active sessions.

**Comment by dougwilson** [comment]
Without understanding more about your app, nothing sounds wrong with that.

**Comment by bonesoul** [comment]
here is my setup;

```
'use strict';

const config = require('config');
const mongoose = require('mongoose');
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);

exports.session = function () {
  let sessionStore = new MongoStore({
    mongooseConnection: mongoose.connection,
    autoRemove: 'native',
    ttl: 7 * 24 * 60 * 60, // 7 days - time to live for session cookies stored.
    touchAfter: 1 * 60 * 60 // save to database every hour.
  });

  return session({
    secret: config.get('backend.session.secret'), // session secret
    resave: false, // Forces the session to be saved back to the session store, even if the session was never modified during the request.
    saveUninitialized: false, // Do not save uninitialized sessions to store.
    store: sessionStore, // store to save our sessions.
    unset: 'destroy', // destroy the session on unset.
    cookie: {
      secure: true,
      httpOnly: true,
      domain: 'buharmetre.com'
    }
  });
};
```

do you see anything strange @dougwilson that may cause the issue?

**Comment by joewagner** [comment]
@bonesoul nothing looks wrong with the code you provided.  the `resave` and `saveUninitialized` options don't do anything if your session is modified on each request.  Usually issues like yours have something to do with another middleware using the session on every request.  This is often [Passport.js](http://passportjs.org/) or something like it.  Unless you can provide a small working piece of code it will be hard to help you.
Is it possible that you just have a lot of sessions?

**Comment by bonesoul** [comment]
nah, i only have 1k of users daily. i'm trying to strip down my code and will post it here.

**Comment by dougwilson** [comment]
Yea, ignoring the Mongo parts that I'm not familiar with, nothing looks wrong to me, either. @bonesoul understanding the information @joewagner mentioned will help a lot. Also what may help a lot is understand how exactly the 1k users daily number is calculated as well, especially since that is what is driving your question.

**Comment by santhosh77h** [comment]
@bonesoul and @dougwilson it may be because not calling req.session.destroy or it can also happen that on each request your making to the server without credentials express may think that session is not set and would set again check this link from [stackoverflow](https://stackoverflow.com/questions/22349645/how-to-delete-express-session-cookie)
