### ISSUE TITLE
req.session.destroy() gives "The DEL command contains a "undefined" argument"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [expressjs/session#435]
This happens whenever I do req.session.destroy()

node_redis: Deprecated: The DEL command contains a "undefined" argument. 
Mar 07 11:07:51 stardust-backend app/web.1:  This is converted to a "undefined" string now and will return an error from v.3.0 on. 

Please advise

**Comment by dougwilson** [comment]
It may be a question for the store module you're using, since this module doesn't directly make and Redis commands. Have you tried opening an issue on your store module yet?

**Comment by GeoffreyPlitt** [comment]
I'm just using "connect-redis" for my store, like everyone else.

It's clear from the error message above that this library (session) is asking redis to delete an undefined key, which seems like a bug in this lib, not the store.

**Comment by dougwilson** [comment]
Yea, I don't disagree, which is why I tagged it as "investigate" here :) but I wanted to know if someone had more details on exactly what is happening. Is it possible to make a test case that reproduces the issue, including the versions of Node.js + the modules so I can dig into it?

**Comment by GeoffreyPlitt** [comment]
sweet, I'll try to throw that together, it's in a private repo now

**Comment by dougwilson** [comment]
Cool. A really, really quick assessment looks like it's because the `connect-redis` straight up passes the `callback` argument to `req.session.destroy()` to the redis command, and since you didn't specify a callback, it's going through as `undefined`. A quick check would be to see if you get the error with `req.session.destroy(function(){})` or not. If not, I think that `connect-redis` would either need to (a) make the `callback` required, (b) pass an empty function to the `.del()` command or (c) call `.del` as `.del(sid, cb)` when there is a `cb` otherwise `.del(sid)`. It seems like the `node_redis` is iterating through all given `arguments` looking for an undefined.

**Comment by GeoffreyPlitt** [comment]
Oh that totally helps! I'm not passing a callback yet. Will try that-- and I'll close this since that makes total sense and is likely the fix, thanks.
