### ISSUE TITLE
share cookie in domain and subdomain on a LAN

### ISSUE THREAD

**Issue by mepdr** [expressjs/session#459]
On a LAN network, two applications requires to share the same cookie.
- http://app1.app_name --> responds application 1
- http://app2.app_name --> responds application 2

Session is configured as follows:
```
app.use(session({ secret: config.secret, 
                  cookie: { domain:'.app_name'},
                  expires: new Date(Date.now() + (60 * 60 * 24 * 7 * 1000)),
                  store: redisStoreClient,
                  resave: true,
                  saveUninitialized: false
                }));
```
With the above configuration users are not recognized as logged in. The leading dot in the domain option doesn't work, removing the dot doesn't work either.

**Comment by gabeio** [comment]
The cookie should be shared between the 2 subdomains, if it is not that's a browser issue but I don't think that is the issue here. There are other options assuming the browser is sharing the cookie between the 2 websites. Are both applications running off of 1 redis instance? Are both applications being supplied with the same config.secret?

**Comment by knoxcard** [comment]
I am currently experiencing the same issue with Redis sessions.

**Comment by mepdr** [comment]
@gabeio yes to both questions. The redis instance and config.secret are the same

**Comment by dougwilson** [comment]
Hi @mepdr the domain option is just passed to the web browser, so it is up to the browser to actually store a cookie in the proper location in order to share. I can take a look, but need to setup an environment to replicate your issue so I have something to poke & debug to figure it out. Can you provide the following?

1. A complete app that demonstrates the issue.
2. Instructions for exactly how to setup the app.
3. Instructions on what actions to take to replicate your issue.

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by happilymarrieddad** [comment]
@dougwilson 
Hey man, 

I was wondering how to setup the domain in the cookie so that 2 subdomains can share the same session. This is what I'm doing currently and it's not working. I want it to essentially do all subdomains on a single domain. I own the *.<domain>.com ssl cert and the full domain.

`let sess = {
            key:config.ssl.session_secret,
            secret:config.ssl.session_secret,
            store: new MySQLStore({},pool),
            proxy:true,
            secure:false,
            ephemeral:false,
            resave:false,
            saveUninitialized:false,
            cookie:{ maxAge:SIXTEEN_HOURS }
        }

        if (config.ENV == PRODUCTION) {
            app.set('trust proxy',1)
            sess.secure = true
            sess.cookie.secure = true
            sess.cookie.domain = '.fusionware.com'
        }

        app.use(session(sess))
`
