### ISSUE TITLE
Change session store database connection on router demand

### ISSUE THREAD

**Issue by calebeaires** [expressjs/session#479]
I have on app project that connect to a distinct MySQL by user demand. This application use MySQL session to create temporary tables per MySQL distinct database connection. I have i have succeeded created session when app starts, but this app really need to change the [session store implementation](https://expressjs.com/en/resources/middleware/session.html#compatible-session-stores) module when a different MySQL connection is need by user. 

1. First -> create app and implement session store middleware like express documentation
2. Tried to change session store on router demand

I have tried to change the **session store** like this:

```node
router.get('/v1/:databaseName', function (req, res, next) {

    const databaseName = req.params.databaseName

    const conn = Knex({
        client: 'mysql2', connection: {
            host: 'localhost',
            password: 'root',
            user: 'root',
            database: databaseName,
            port: 3306
        }
    });

    const store = new KnexSessionStore({
        knex: conn
    });

    req.session.save(function () {
        req.session.store = store
        // do things from here with a brand new session store

    });

});

```
How to use session store module on demand?

**Comment by dougwilson** [comment]
I'm not really understanding what you're trying to do, but at least the high-level issue in your example is that `req.session.store = store` is not going to change anything. If you do `req.sessionStore = store` it will actually change the store for the rest of that request / response cycle.

**Comment by a-eid** [comment]
@dougwilson  could you explain why `req.session.store = store` wouldn't change anything . and why `req.sessionStore = store` would . 

one more thing does that mean that whenever I need to store info in session I need to attach it directly on the `req` ?

**Comment by dougwilson** [comment]
> could you explain why req.session.store = store wouldn't change anything . and why req.sessionStore = store would .

Because nothing in this module ever uses that property. You may as well do `req.session.gobblegobble = store` and it would have the same effect. If nothing uses it, then it won't do anything.

> one more thing does that mean that whenever I need to store info in session I need to attach it directly on the req ?

I'm not sure what that means. All your session data is stored under `req.session`.

**Comment by a-eid** [comment]
so how do I store info on the user session .. 

I've been trying to persist data on session and it doesn't work . 

```javascript 
app.get('/auth' , (req , res) => {
  req.session.loggedin = true 
  res.redirect('/loggedin')
})

app.get('/loggedin' , (req ,res) =>{
  res.json({
    loggedin: req.session && req.session.loggedin ? true : false
  })
})
```

even after hitting the `/auth` route `loggedin` property is false .

**Comment by dougwilson** [comment]
You cannot store database information in the session, since you need to know the database information in order to first look up the session to get the database information.

As for why that isn't working, I'm not sure. Does the example in the README work? If so, perhaps can you provide the full app that isn't working and I can try to debug it with you :)

**Comment by gabeio** [comment]
@a-eid might I suggest opening a new issue I believe your issue is not related to the op on this issue.

-----

@calebeaires I believe we do not have anything setup in a way that you could switch sessions stores on a per request basis. @dougwilson ideas on how that might be achieved? Maybe the best option there would be to not attached the session directly to the app globally and pass the request later to a session instance depending on the request?

**Comment by dougwilson** [comment]
I think we need a better understanding to see if it's even possible to achieve. For example, if you have user sessions and want different users to use different stores, in order to look up any information in the session when a new request comes in, you get the session ID and then you have to query _something_ in order to get the location for where to get the session data from.

**Comment by gabeio** [comment]
True.
(This is now me just carrying the ball.) If say, you wanted the user to be logged into 2 different session stores, say 1 global and then 1 for extra data is it possible to pass the request through a second store (assuming you have 2 differently named cookies for the sessions)? I assume so right?

**Comment by calebeaires** [comment]
Thanks for the answers. 

I tried to approach this issue using the MySQL session itself, but I have found that it were not a good solution at all. My app (Gaio Platform) works with many database players to flow data to the MySQL. On there I must make control with session to turn data unique to each user. 

Here is the issue I have open on the MySQL community (https://github.com/sidorares/node-mysql2/issues/606).

**Comment by dougwilson** [comment]
So I'm not sure if this issue is going anywhere. Can someone volunteer to make a pull request to implement whatever would be required to make this work? Or at least outline what changes would need to be made to the module to support this?

**Comment by calebeaires** [comment]
My solution were to handle the session with another way, the mysql session itself.

**Comment by dougwilson** [comment]
I'm going to close this since it doesn't seem to be going anywhere. There isn't enough information to make the changes on this end, so perhaps if someone can volunteer to make a pull request to implement whatever would be required to make this work or at least outline what changes would need to be made to the module to support this that would be a good path forward.
