### ISSUE TITLE
Broken responses if store never finished or custom error handler calls send and next

### ISSUE THREAD

**Issue by tuhoojabotti** [expressjs/session#492]
Okay so this is a user error, because you don't need to call `next(error)` after calling `res.send(myError)`, but I wanted to post here in case someone is debugging the same problem. Hopefully it can be caught in express-session, too.

If saveUninitialized is true, for some reason a custom error handler can cause responses to break.

Here's the code:

```js
const { EventEmitter } = require('events');
const express = require('express');
const session = require('express-session');

const app = express();

const store = new class extends EventEmitter {
	constructor() { super(); this.sessions = new Map(); }
	all(cb) { process.nextTick(() => cb(this.sessions.values)); }
	get(id, cb) { process.nextTick(() => cb(this.sessions.get(id))); }
	set(id, s, cb) {
		// Comment this line to try timeout.
		setTimeout(() => { this.sessions.set(id, s); cb(); }, 100);
	}
	length(cb) { process.nextTick(() => cb(this.sessions.size)); }
	destroy(id, cb) { this.sessions.delete(id); process.nextTick(cb); }
	clear(cb) { process.nextTick(() => { this.sessions.clear(); cb(); }); }
	touch(id, cb) { process.nextTick(cb); }
};

app.use(session({
	secret: 'foobar',
	resave: false,
	saveUninitialized: true,
	store
}));

app.post('/broken', (req, res, next) => {
	next(new Error('Invalid password.'));
});

app.use((err, req, res, next) => {
	res.send({ error: err.message });
	next(err); // <- This breaks express-session
});

app.listen(8888, () =>
	console.log('Server listening at', `http://0.0.0.0:8888`));
```

Here's the response:

```
$ curl -H "Content-Type: application/json" -X POST http://localhost:8888/broken
curl: (18) transfer closed with 1 bytes remaining to read
{"error":"Invalid password."%
```

If you turn off `saveUninitialized` it works, if you remove `next(err)` it works unless you comment out the callback in the `Store.set` command and the request times out.

For reference I first thought that this issue was in tj/connect-redis#211

**Comment by dougwilson** [comment]
Hi @tuhoojabotti thanks for the through report and code! Unfortunately there isn't anything express-session can do in this case. You see, in your code that very last `next(err);` call is invoking the internal Express.js "last resort" error handling mechanisms. Part of this is that it checks to see that a response has already been started, in which case, since it cannot itself now write the error response, it panics and just destroys the socket, as you cannot be sure if the response will ever finish (as the error may have stopped some code that was trying to write the response).

The reason why in your example changing `saveUninitialized` affects the results is because when `saveUninitialized` is `true`, it will always try to save the session to the store, which takes time to occur (thus leaving some time for Express.js to destroy the socket on your error call). When it is `false`, it will only save the session if you modified it, which in your case you didn't, thus not trying to save any session and not setting and session cookies on the response.

I hope that makes sense!

**Comment by tuhoojabotti** [comment]
Yes that makes a lot of sense, I removed the next call from our codebase and added a big comment saying not to add it back. :) I just hope that if someone is getting is weird error will be able to find this issue via a Google search. We first assumed the error was in the load balancer http2 implementation and then we thought babel broke something, until we realised that the problem only occurred if redis was used to store sessions and then figuring out why was quite a chore.

Also the same error happens if the store never finishes saving the session, maybe there should be some kind of timeout that express-session will assume that the store is down and continue without cutting the response?

**Comment by dougwilson** [comment]
So right now functionality like timeouts are left up to the stores to implement, as they would have the ability to set timeouts on their underlying sockets and actually cancel activities when the timeout occurs. If you think maybe this module could implement the functionality, please feel free to submit a pull request with an implementation :)

**Comment by tuhoojabotti** [comment]
I think that separation of concerns is good. Thank you for your responses!
