### ISSUE TITLE
TypeError: first argument must be a string or Buffer

### ISSUE THREAD

**Issue by david-knipe-camlin** [expressjs/session#503]
I've got the following stacktrace:
```
TypeError: first argument must be a string or Buffer
at ServerResponse.OutgoingMessage.end (_http_outgoing.js:549:11)
at writeend (/usr/share/my_project/node_modules/express-session/index.js:261:22)
at onsave (/usr/share/my_project/node_modules/express-session/index.js:335:11)
at ...
```
The problem is that when `.end()` is called on the wrapper `ServerResponse` generated by express-sessions, it calls `.end(undefined, undefined)` on the underlying `ServerResponse`. The former method call conforms to the interface of `ServerResponse`; the latter does not.
express-session v1.14.1, nodejs v4.4.7.

**Comment by dougwilson** [comment]
Hi @david-knipe-camlin calling `.end(undefined, undefined)` is a valid call, because you can see the Node.js check here: https://github.com/nodejs/node/blob/v4.4.7/lib/_http_outgoing.js#L549

When the first argument, `data` is `undefined`, it will never enter into that `if` statement, because the first check is not satisfied (`undefined` is not true).

Is it possible you can provide a test case so we can reproduce the issue to determine what is occurring? Otherwise you're always welcome to make a pull request with a fix, though you'll still have to make a test case so we have a test in our test suite to ensure we don't regress.

**Comment by david-knipe-camlin** [comment]
That's true... I have seen that stacktrace, but it's hard to reproduce so I'm not sure exactly what's going on. You make a good point. I'm going to change my story slightly: It was probably `res.end(500);` that made it throw.

**Comment by david-knipe-camlin** [comment]
Wait a minute... Is `res.end(500)` even a thing? I don't see it in the documentation for `ServerResponse`; yet it's been in our code since March, and it does look kind of familiar.

**Comment by dougwilson** [comment]
The `res.end` method is from the Node.js core itself (https://nodejs.org/dist/latest-v4.x/docs/api/http.html#http_response_end_data_encoding_callback). I'm not sure if it used to take a number or not (regardless of their documentation). Did you change your Node.js version at all?

**Comment by david-knipe-camlin** [comment]
No, I didn't. I suspect the guy who wrote `res.end(500)` didn't realise that it doesn't exist any more, and forgot to test the error case. So feel free to close this.
