### ISSUE TITLE
How to handle session store error

### ISSUE THREAD

**Issue by dahiyaDeepak** [expressjs/session#538]
Hi, 

I am trying to use dynamodb store with express-session. 

The problem I am facing is if sessionStore.set is failing for some reason, the user is still getting the response back with 200 and I am not able to send error by catching in middleware as headers are already sent in session.save in index.js file.

Please advise how to handle session store (async) errors.

Thanks
Deepak

**Comment by dougwilson** [comment]
Since the error isn't happening until after you started sending the response Node.js doesn't provide a mechanism to change it as you can see.

You need to manually call req.session.save before writing the response if you want to be sure there won't be any session errors after you write a response.

I hope that helps!
