### ISSUE TITLE
getcookie back-compat implementation incorrect for signed vs unsigned

### ISSUE THREAD

**Issue by d3zza** [expressjs/session#540]
Seems like getcookie ( index.js line 512 ) is trying to read unsigned cookies from signed cookies and vice-versa if cookies not present in header

See [PR](https://github.com/expressjs/session/pull/539)

**Comment by dougwilson** [comment]
I'm not quite sure I understand. The `req.signedCookies` contains the unsigned value, which is what we're reading. The `cookie-parser` module (which populates these objects) won't populate `req.signedCookies` with the value that includes the `s:` part (because it will strip that). The `req.cookies` would contains the "raw" value that would still have the `s:` part so we need to unsign it. The code at the time it was added replicated the old behavior and there are tests that force the use of `cookie-parser` to check this. Can you elaborate on what you mean, exactly?

**Comment by d3zza** [comment]
Hi @dougwilson, maybe I'm misunderstanding how it's supposed to work. I thought that the code would be trying to unsign values in req.signedCookies, and just retrieve values as is from req.cookies.

Background on my situation/issue: 
I am using [express-socket.io-session ](https://github.com/oskosk/express-socket.io-session) which stores cookie (sessionID in my case) in req.cookies.

In my proj express session never finds the sessionID and the net effect is that new session ids keep getting created when sockets reconnect.

Or am I missing something? Thanks

**Comment by dougwilson** [comment]
Hi @d3zza I guess you may misunderstand. The values in `req.signedCookies` are the cookie values that were successfully unsigned, so thus no longer have signed values. The `req.cookies` contains the raw cookie values from the `Cookie` header, so thus signed cookies would still be prefixed with the `s:` string. I'm not familiar with that module so really have no idea regarding it, unfortunately.

The `req.signedCookies` and `req.cookies` objects are expected to be populated by our `cookie-parser` module, so we read the values as that module has always populated the objects. If another module populates them in a different way, I'm not sure, but this is the main reason reading from those objects is deprecated :)

**Comment by d3zza** [comment]
Ok I see. I think the problem is that the module in question is populating the wrong object. Please ignore PR and I'll take it up with them. Thanks

**Comment by dougwilson** [comment]
Ok. I can also always take a look if you can provide all the following so I can debug the issue, of course:

1. Version of Node.js
2. Version of this module
3. Version of that module
4. Full server code I can copy and paste and run
5. Full instructions for how to setup the server and step by step instructions for how to trigger the issue (for example "open browser to ..., then click ..., then you'll see ....")

**Comment by d3zza** [comment]
Quick question: Is cookie data created by expressjs/cookie-parser compatible with expressjs/session ? Because that is what the module in question is using

**Comment by dougwilson** [comment]
The `cookie-parser` doesn't generate any data; it's just a parser. There is a large group of tests in this module that use `cookie-parser` to do the parsing without issue, so they are compatible, yes. That is the purpose of the code in question, to read the data and objects that the `cookie-parser` module creates.

**Comment by d3zza** [comment]
I realise my mistake. The module in question uses it's default cookie parser which did not have the secret i configured express session with. It can be made to work by giving it a cookieParser instance with the same config. Thanks for your help

**Comment by dougwilson** [comment]
Oh, I see. I think I may understand what you're seeing with that description. Since `req.signedCookies` only contains the unsigned cookies, if that cookie was singed, but not with a signature that matched the known secret, it won't get included in `req.signedCookies` as it looks like a tampered value.
