### ISSUE TITLE
Error: Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by creativenoobie** [expressjs/session#565]
Hey,

I'm planning to use sessions in my Nuxt application instead of relying on cookies for data storage.

Here's my code (plugin/express-sessions.js)
```
import Vue from 'vue'
let cookieParser = require('cookieparser')
let session = require('express-session')
var Memorystore = require('memorystore')(session)

var sessionConfig = {
  secret: 'asdnsadnda',
  resave: 'false',
  saveUninitialized: 'false',
  cookie: {},
  store: new Memorystore({
    checkPeriod: 86400000
  })
}

Vue.use(cookieParser)
Vue.use(session(sessionConfig))

```
here are my actions (store/index.js)

```
const actions = {
  nuxtServerInit ({ commit }, { req }) {
    console.log(req.session)
    if (req.session && req.session.authUser) {
      commit('SET_USER', req.session.authUser)
    }
  },

  login ({ req }, { commit }, payload) {
    req.session.authUser = payload.user
    commit('SET_USER', payload.user)
  }

}
```
here's my nuxt.config.js
```
plugins: [
    '~/plugins/vuetify.js',
    '~/plugins/express-sessions.js'
],
 build: {
    vendor: [
      '~/plugins/vuetify.js',
      'express-session',
      'babel-polyfill'
    ]
...
```
Here's what I'm facing now:
![image](https://user-images.githubusercontent.com/23532769/37372397-9c150d48-2738-11e8-9a41-7167c488ce18.png)

Any ideas what might be wrong?

Please help me!

**Comment by dougwilson** [comment]
I think that would only happen if there is no req.url set. Can you log that property to see what the value is?

**Comment by creativenoobie** [comment]
console.log(req.url) returns `/`

**Comment by creativenoobie** [comment]
Please note that I had to delete the code from express-sessions.js in order to compile it properly or else it would return the same error.

**Comment by dougwilson** [comment]
Hm, weird. Can you help provide instructions on how I can run this to reproduce the issue so I can debug it? I tried copying the first thing but Node.js errored on the import part. I'm not familiar how that nuxt file comes into play, either.

**Comment by creativenoobie** [comment]
Hey,

You can use vuetify nuxt template: https://github.com/vuetifyjs/nuxt

Also, attaching couple of YouTube tutorials to help you with the same:
https://www.youtube.com/watch?v=nteDXuqBfn0
https://www.youtube.com/watch?v=ZYUWsjUxxUQ

**Comment by creativenoobie** [comment]
Can you share your email with me? I'll mail you my source code to make things easier?

**Comment by dougwilson** [comment]
Hi @creativenoobie you can find my email address in my GitHub profile: https://github.com/dougwilson

**Comment by creativenoobie** [comment]
Hi @dougwilson 

I have emailed you my project files. Please check.

**Comment by dougwilson** [comment]
Hi @creativenoobie I haven't gotten anything yet. Did you just sent them now, or hours ago?

**Comment by dougwilson** [comment]
Thanks @creativenoobie ! I got your email now, but since I don't have an easy way to open and run this on my phone, I'll have to wait until I get home in about 8 hours to download and view it 👍

**Comment by dougwilson** [comment]
Hi @creativenoobie I tried to follow your directions, but your instructions end but I don't see any errors:
<img width="1367" alt="screen shot 2018-03-14 at 12 10 03" src="https://user-images.githubusercontent.com/67512/37414961-b580a13c-2780-11e8-8043-9f5736cbaf88.png">

**Comment by dougwilson** [comment]
Ok, I see the error is in the web browser console:
<img width="743" alt="screen shot 2018-03-14 at 12 16 03" src="https://user-images.githubusercontent.com/67512/37415318-8e6d946e-2781-11e8-9b90-8d77e589b7fc.png">

You can see in the image above, I attached a debugger. The `req.url` is `undefined`, just like I expected, which is why you get the error. In fact, the `req` object is some weird Vue object and not a HTTP request object and `res` and `next` are both undefined. I'm not familiar with Vue / nuxt and what you're trying to do, so don't know how to direct you.

The best I can say as the author of this module is that you're not invoking the returned middleware with the proper arguments an Express.js middleware expects: You need to provide three arguments: `req` = HTTP request object, `res` = HTTP response object, and `next` = function to move to the next middleware. Your code is calling it with just one argument, some `Vue` object, which is triggering the error.

**Comment by creativenoobie** [comment]
@dougwilson Thank you so much for troubleshooting in detail.

As it turns out, `req.url` is available only in store and not on frontend.
