### ISSUE TITLE
Multiple entries on first request

### ISSUE THREAD

**Issue by mercmobily** [expressjs/session#568]
Hi,

Thanks for the awesome module.
I am having an issue where in the very first request, I end up with 5 records rather than 1.
I am using express-mysql-session and node-prpl as the server.

    mysql> select * from sessions;
    +----------------------------------+------------+-------------------------------------------------------------------------------------------+
    | session_id                       | expires    | data                                                                                      |
    +----------------------------------+------------+-------------------------------------------------------------------------------------------+
    | P2Oo3L61Spc2MeKo-ruQGgXZ3zHQ0IPl | 1521520778 | {"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"stocazzo":1} |
    | ZqdBPicBaBFga-Ig9LOg_qyMACLhPgsK | 1521520778 | {"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"stocazzo":1} |
    | e8TFHpmMuq2LgZFTbaGWBacUmRiip8QB | 1521520778 | {"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"stocazzo":1} |
    | myD8SrfvBsYHEOVM2vwsP0Vu0DST0jFq | 1521520778 | {"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"stocazzo":1} |
    | rB2wVLKyYHCVA03qlk2a9GhQ5qgGpCgt | 1521520778 | {"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"stocazzo":1} |
    +----------------------------------+------------+-------------------------------------------------------------------------------------------+

I did some debugging, and I figured out that it's happening because the server is receiving several requests at the same time. As a result, by the time request 2 arrives, request 1 hasn't yet created an entry in the database.

I can provide more information but... is this the expected behaviour? If not, how do I mitigate it? If yes, shall I have a script to get rid of the "old" unused sessions?

Thanks again

**Comment by dougwilson** [comment]
What do you have the https://github.com/expressjs/session/blob/master/README.md#saveuninitialized setting set to? Choosing false should resolve the issue you are experiencing.

**Comment by mercmobily** [comment]
(Thanks Doug, we should build you a statue)

I am afraid I already have it as `false`:

    // Make up the session
    app.use(session({
      key: 'sasit',
      secret: '(deleted)',
      store: sessionStore,
      resave: false,
      saveUninitialized: false
  }))

**Comment by dougwilson** [comment]
Yea, I just noticed your sessions above all have "stocazzo":1 so that wouldn't help since you're modifying all those sessions. What are the multiple parallel requests for? What does the stocazzo = 1 mean in your sessions? Is it possible to only set that value on the session for requests that represent a page, for example?

**Comment by mercmobily** [comment]
Ahhhhhhhhhhhhhhhhh I get it. That was a variable (with a rather embarrassing name -- let's not even talk about that) that I placed there for testing purposes.
Taking it out, I have an EMPTY table -- which is right, since I haven't put anything there yet.

I am writing the login script now. I am sure once I set `loggedIn` as `true`, it will save it for that one session.

Closing for now, I very much doubt I will reopen it.

When I grow up I want to be like you Doug :D

**Comment by dougwilson** [comment]
Happy to help. Yea, that sounds like the right path. Requests without a cookie would then just have an empty session object until a login occurs, at which point setting a value in the session will create a session and set a cookie. Since the login process itself will be a single request, it avoids the race condition issue.

Other easy wins are if you are serving static files in your Node.js app you can do that before the session (at least for files you're not going to gate to a session) or if you only need the session for a subset of the site to mount it just for those routes. This has the added benefit of skipping database queries when you're not going to need the session anyway :+1:

I hope this helps!

**Comment by mercmobily** [comment]
It does it does. Thanks a gazillion!
