### ISSUE TITLE
Session generation appears to be asynchronous

### ISSUE THREAD

**Issue by Aman40** [expressjs/session#570]
Focus on the `send_session_data` function at the end. In the `else` part, without the `res.write("<msg>You're not logged in</msg>");` statement, `${res.getHeader('Set-Cookie')}` returns `undefined`. The other way to get it to work is to use a `setTimeOut` function with even just a few milliseconds to provide overhead, or "buy time" for the session to be generated. Only then will the `${res.getHeader('Set-Cookie')}` statement contain the cookie. Now, I don't know if it's the default `genid` function, but something is asynchronous during the generation of the the session, yet it doesn't inherit the `eventEmitter` class. Did I miss something? Source file is attached. 
[proof.js.gz](https://github.com/expressjs/session/files/1844446/proof.js.gz)
[proof.txt](https://github.com/expressjs/session/files/1844447/proof.txt)

**Comment by Aman40** [comment]
PS: How do I add tags like "need help"

**Comment by dougwilson** [comment]
What you are seeing is correct; the cookie is not set on the response until you save the session. If you do not call req.session.save to save it, this module will automatically do so when you start writing a response. Calling req.session.save will set the cookie if you need it earlier.

**Comment by Aman40** [comment]
So it's not a bug; It's a feature? Haha thanks a lot!!
Also, may a mention of it be made in the documentation, preferably around the **Session.save(callback)** heading? ありがとうございます。

**Comment by dougwilson** [comment]
Yea, we'll get it documented. There is ko documentation at all around when you should expect the Set-Cookie to be on the response object and it was never documented before because (1) no one has never asked before to get the Set-Cookie header and (2) we felt like that was an internal implementation detail no one would be trying to get at.

You're always welcome to help out and write up the documentation on Set-Cookie :+1: but we'll get it documented regardless, no worries. Happy to answer your question.
