### ISSUE TITLE
What if I don't want to sign the cookie?

### ISSUE THREAD

**Issue by gh67uyyghj** [expressjs/session#579]
Hi all and thanks for this very important package, I will use strict HTTPS in production so as far as I understand signing the cookie will be redundant and useless in this case since the integrity of the entire HTTP message will be verified at the TLS level. But also I see that the `secret` option is required here. Is there any way to disable signing the cookie or is this a hardwired functionality?

**Comment by dougwilson** [comment]
It is not possible to turn off by design.  Even using HTTPS completely doesn't cover all the different attack vectors. You can find many resources online for why the session id should be signed. I just grabbed one from google real quick: https://funcptr.net/2014/06/10/tamper-proof-session-cookies-and-session-storage/

**Comment by knivets** [comment]
If the function that generates the session ID is good enough then signing the ID provides no additional security https://security.stackexchange.com/a/89548/28219
