### ISSUE TITLE
Incorrect server date

### ISSUE THREAD

**Issue by ffamar** [expressjs/session#584]
Hello,
I use express-session module in a embedded device. When the target has a date set in the past (Eg. due to battery fail), Firefox and Edge don't accept cookie session, chrome doesn't have any problem.
I see that in the header of page, the module does never send max-age attribute, it send only expired attribute, this happens because cookie module doesn't return maxAge but return originalMaxAge:
```js
  get data() {
    return {
      originalMaxAge: this.originalMaxAge
      , expires: this._expires
      , secure: this.secure
      , httpOnly: this.httpOnly
      , domain: this.domain
      , path: this.path
      , sameSite: this.sameSite
    }
  }
```
I added attribute 
```
maxAge: this.originalMaxAge 
```
and It seems that this patch solves the problem in firefox but not in edge.

Can you help me, please?
Thanks
Fabio

**Comment by dougwilson** [comment]
Currently this module only works setting the cookies when your server has the correct date / time. I'm not super familiar with all the particularities of all the various browsers, but as for max-age vs expires, it currently only sets expires because this has the widest browser support, where there are still ones in use that don't support max-age and ones that with both max-age and expires are there don't work correctly.
