### ISSUE TITLE
Secure cookie wrong definition; not set if http request

### ISSUE THREAD

**Issue by James2516** [expressjs/session#625]
From the [docs](https://github.com/expressjs/session#cookiesecure):
> If secure is set, and you access your site over HTTP, the cookie will not be **set**.

However, the [definition of secure cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) is:
> A secure cookie will only be **sent** to the server when a request is made using SSL and the HTTPS protocol.

This library seems to avoid **setting** the secure cookie completely (no `Set-Cookie`) if the request is not secure, but the spec says that the cookie should still be **set** (with the `secure` flag) in the response to the unsecured request; it is the duty of the browser to not **send** secure cookies over http.

**Comment by dougwilson** [comment]
Reading through the MDN article you linked I see it says

> Starting with Chrome 52 and Firefox 52, insecure sites (http:) can't set cookies with the "secure" directive anymore.

Which sounds like it is reinforcing the behavior this module is doing, because if browsers now will not even set them if the have the secure flag over an insecure connection, surely the web server should not even bother sending them, as they will be immediately rejected (besides the fact that they would be compromised by sending over clear text already).

**Comment by James2516** [comment]
Sorry you are right, the spec wasn't clear on this but the current implementation makes sense.
