### ISSUE TITLE
Express Sessions without app.use, specifically for Google Cloud Functions?

### ISSUE THREAD

**Issue by jake-tulip** [expressjs/session#626]
There don't seem to be any examples where sessions are passed in not as a middleware, but just used as is. Also, we would need to use a backend like Google Cloud Datastore or CloudSQL as a backend, because GCF is serverless.

The problem is Google Cloud Functions, you don't have access to the `app.use` variable.

Are there any best practices for solving this problem of sessions in a serverless environment without access to the root Express object?

**Comment by dougwilson** [comment]
There aren't any examples since this module only provides a single export: a middleware function for use with app.use in express.

I'm not really familiar with the Google Cloud Functions so don't know what the solution would be for you.

If this module were to support that environment, what kind of changes would need to be made to support it? That would likely help the discussion to understand what the ask is here.

**Comment by jake-tulip** [comment]
> If this module were to support that environment, what kind of changes would need to be made to support it? That would likely help the discussion to understand what the ask is here.

The only issue is that serverless (Google Cloud Functions, AWS Lambda) usually won't expose the `app` Express object directly.

The only changes would be a way to use the `sessions` object, but not as a middleware.

Maybe call it as a standalone function like `session(...)` and have it replicate the handler functions.

Not sure how feasible this is, but thank you @dougwilson for clarifying that this is a nonstandard usecase.

**Comment by dougwilson** [comment]
Thanks for the clarification. It sounds to me like that could be it's own module, especially since this module's name includes the word "express". From looking at docs on Lambda and Google, they are not using Express.js at all and instead are simply trying to mimic it's API to make it easier for developers who are familiar with the Express.js API. This is likely why you cannot use middleware, as they didn't implement that feature (yet?).

Especially given they are not using Express at all, it's likely out of scope for this module to support.

**Comment by jake-tulip** [comment]
One last question @dougwilson 

Calling the code manually such as:

```
const session = require('express-session')

// Google Cloud Function
exports.middleware = (req, res) => {
  const s = session({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: true,
  cookie: {}
  })

  s(req, res, () => {
    req.session...
  })
}
```

Seems to set the `connect.sid` Cookie on response, which to me seems like this works as a solution, and `req.session` is accessible in the `next()` function.

Do you see any issues doing it this way?

I understand as you said that it's possible Google and Amazon don't use ExpressJS (I thought they did use it under the hood, but a less complete implementation), so I just wonder if there is any issue in essentially inlining the Express middleware functionality of `next()` like this you might see.
