### ISSUE TITLE
cookie.secure does not work.

### ISSUE THREAD

**Issue by aprilmintacpineda** [expressjs/session#628]
The following works perfectly:

```js
app.use(
  require('express-session')({
    secret: uuidv4(),
    name: 'session',
    rolling: true,
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      secure: false,
      path: '/',
      expires: new Date(Date.now() + 3600000)
    }
  })
);
```

Note that `secure` is set to false. I'm using this library together with [csurf](https://github.com/expressjs/csurf). When secure is set to false, it works fine, but when it's set to true, it no longer works. `csurf` would throw `ForbiddenError: invalid csrf token` and the reason is because the csrf token that is being saved on the session is not being saved.

- I'm using ALL LIBS@LATEST
- My app is running on a testing production environment on heroku under https://[app].herokuapp.com . What I want to emphasize here is that the app is running under subdomain, but still https.

**Comment by dougwilson** [comment]
Hi! Sorry you're having problems. Since you didn't mention it yet, I just wanted to check as a first step: did you configure the trust proxy in express outlined in https://github.com/expressjs/session/blob/master/README.md#cookiesecure ?

**Comment by aprilmintacpineda** [comment]
after setting `trust proxy` to `1`, it worked as expected. Why is this necessary though?

**Comment by dougwilson** [comment]
Sorry, didn't mean to click any button. Was just reading your question,  though I am out right now and can't respond with a thorough answer for a week or so.

**Comment by dougwilson** [comment]
Sorry I had forgotten to come back to this earlier.

The reason this is necessary is for a security issue that had to be resolved in a module below this that sets cookies. Many servers are misconfigured (or configured on purpose) to serve over both http and https. Sending a cookie you want to be secure over an insecure connection from the server compromises the integrity of the cookie and the RFC for cookies explicitly recommends that the server should not send cookies with a secure flag over an insecure connection.

For security purposes, this was implemented here as a secure default. To get secure cookies to send, you need to configure Express to be aware of a reverse proxy if your Express server is not directly using a secure connection, as it otherwise as far as it knows you are using an insecure connection.
