### ISSUE TITLE
Rolling session prevents logout

### ISSUE THREAD

**Issue by TimboBl** [expressjs/session#640]
I have set the rolling flag to true as well as resave as can be seen below. However, whenever a user tries to logout of my app, the session is being renewed. 
I have to have resave enabled because otherwise there is no rolling session. However, the user should still be able to logout. 
I am using express-session with passportjs. I call req.logout() as well as req.session.destroy() just to be sure to destroy it for real. Neither work alone and together the user is a least logged out until a page refresh. 

I believe this is a bug and it needs to be fixed.

If I can supply any more information let me know please.

Here is my config:
```javascript
app.use(session({
		secret: SESSION_SECRET,
		store: store,
		saveUninitialized: false, 
		resave: true, 
		cookie: {
			maxAge: 604800000,
			secure: false 
		},
		rolling: true,
	}));
```

**Comment by dougwilson** [comment]
Yea, I can definitely take a look, but would like to be able to reproduce the issue to be able to identify the root cause and then be able to validate that a fix works.

Typically in order to reproduce the issue, I need the following information:

1. Version of Node.js this module and all others used. Ideally minimize the use of any external module, as that significantly delays the investigation due to a lot of things going on an unfamiliarity with third party modules.
2. Complete code I can run without any modification that will reproduce the issue.
3. Steps by steps instructions of what to do with the given code to reproduce the issue.

**Comment by CkFreak** [comment]
Sorry @dougwilson for the super late reply. 
I did not have much time these past two weeks.
[Here](https://github.com/CkFreak/rolling_session_exapmple) is a repository with a simple example only using express and express session. I had to use a react Frontend because I just could not get the cookie transfer to work from a static page because it has no origin.
The Readme should explain everything. If there is anything unclear of bad, please let me know and I will improve!

**Comment by joewagner** [comment]
@CkFreak Sorry to jump in here, but your app doesn't have any notion of logging in that I can find.  The behavior of the rolling flag is to "Force a session identifier cookie to be set on every response".
  Ideally you will set a value on the session indicating that the session is authenticated, and potentially which account is associated with the session.
Here is a variation on your backend that demonstrates what I'm saying
https://gist.github.com/joewagner/0a4600009384d3b9e5a815234376587a

**Comment by knoxcard** [comment]
I believe that @CkFreak is a 100% correct.  I've noticed this issue as well, but it was never because of Express.  You mentioned that "you have to refresh the page" to notice the session change.  Is your app a single page app, are you using websockets or ajax to call your logout() logic?

**Comment by CkFreak** [comment]
It took me really long to understand the difference here. @joewagner is right I believe. I understood the rolling feature like I implemented it. Obviously. But what you mean makes more sense. 

It is a single Page Application and I use ajax to call the logout route.

**Comment by knoxcard** [comment]
@CkFreak - aha.  So if the logout happends upon refresh, everything is working.  On your ajax callback, you have to update your frontend to correspond to the new session update.

Just posting this for everyone else to see as well...
```
req.session <- always exists
req.session.user_id <- you add this when someone is logged in

req.session.destroy(()=> {
   // req.session still exists, but is brand new
  // req.session.user_id no longer exists
})
```

**Comment by knoxcard** [comment]
@CkFreak - close issue? Or more clarification needed?

**Comment by CkFreak** [comment]
I think the issue can be closed. 
Although my page asks the server if the session it has is still valid, which should not be the case after I destroyed it upon the AJAX request to the server. 
Instead though, the server response with 200. It should give a 401 instead. 

I am not sure if your example will solve the issue. Session handling is done on the server and validation of said session as well. My issue is, that the session the user is logging out of, gets destroyed but seemingly instantaneously recreated with all the previous data. I will have to investigate this further but I think for now I cannot do much more.

**Comment by gireeshpunathil** [comment]
close candidate
