### ISSUE TITLE
How do I keep a session variable from changing?

### ISSUE THREAD

**Issue by rdalfonso** [expressjs/session#651]
Seems like no matter what I do the value of req.session keeps changing.

const copySession - req.session.myObject;
const changedCopy = functionThatWantsToChangeTheCopyOnly(copySession);

For some reason even assigning the req.session to a variable, and changing THAT variable, affects the original req.session?

Any ideas why?

**Comment by knoxcard** [comment]
Please post your express-session code, middleware and controller routes.

**Comment by machineghost** [comment]
I asked a similar/related question on Stack Overflow, and I truly believe the answer would help a lot of users of this library: [What Makes Express-Session Decide to Start a New Session](https://stackoverflow.com/questions/55987723/what-makes-express-session-decide-to-start-a-new-session)?

Obviously Stack Overflow is the place for questions, not the issues section of GitHub, but since the people most knowledgeable about this library are here, and since answering this question would also literally answer this issue (and likely others too), it would be tremendously helpful if someone from the project could answer it.

**Comment by knoxcard** [comment]
I must have originally read your question too quickly at first, because I wouldn't have asked you to post your code.

I know that exact problem you are having....

We have all experienced this...

**Comment by knoxcard** [comment]
ere is a simplified illustration that may help you visualize what is happening

// [Object1]<--------- myObj

var tempMyObj = myObj;

// [Object1]<--------- myObj
//         ^ 
//         |
//         ----------- tempMyObj
As you can see after the assignment, both references are pointing to the same object.

You need to create a copy if you need to modify one and not the other.

// [Object1]<--------- myObj

`const tempMyObj = Object.assign({}, myObj);
`
// [Object1]<--------- myObj
// [Object2]<--------- tempMyObj

**Comment by knoxcard** [comment]
@rdalfonso - close issue?

**Comment by rdalfonso** [comment]
Yes I figured it out.
