### ISSUE TITLE
Headers are not set to accept secure cookie

### ISSUE THREAD

**Issue by samteb** [expressjs/session#697]
This issue can be linked to this one #652

Locally everything works fine, and the session cookie is set perfectly.

I have a problem in production, I also use AWS and Cloudfront. 

The headers received by the server are :

```
host : "api.myDomain.com"
accept : "application/json, text/plain, */*"
origin : "https://dashboard.com"
authorization : "Bearer blablabla"
user-agent : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
sec-fetch-mode : "cors"
sec-fetch-site : "same-site"
referer : "https://dashboard.com"
accept-encoding : "gzip, deflate, br"
accept-language : "en-US,en;q=0.9"
cookie : "blablabla"

``` 

And my server middlewares are:

```
// Help to secure express app by setting various HTTP headers
app.use(helmet());

// Set CORS middleware
app.use(cors({
    credentials: true,
    origin: (origin, callback) => {
        if (!origin || origin === 'null' || [ 'localhost', 'myDomain.com' ].some(value => origin.indexOf(value) >= 0)) {
            callback(null, true)
        } else {
            console.log('not allowed by CORS', origin);
            callback(new Error('Not allowed by CORS'))
        }
    }
}));

// Parse incoming parameters requests to req.body
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(bodyParser.text());

// Set Redis session cookie. Track the logged-in user across sessions.
const isProduction = [ 'production', 'staging' ].includes(process.env.NODE_ENV);
if (isProduction) {
    app.enable('trust proxy');
}
app.use(session(
{
        proxy: IsProduction,
        resave: false,
        saveUninitialized: false,
        secret: 'mySecret',
        store: new redisStore({ client: redisClient }),
        cookie: {
            path: '/',
            secure: IsProduction,
            httpOnly: true,
            maxAge: 1000 * 60 * 60 * 10
        },
        unset: 'destroy'
    }
));

```

What I am doing wrong ?

**Comment by dougwilson** [comment]
My guess would be either isProduction is not actually true when deployed there or your x-forwarded-proto is not coming though (http://expressjs.com/en/guide/behind-proxies.html).

Any additional information you can provide regarding either of those will help us improve the guess as to your issue. Connecting a debugger and stepping through the code on your server would also narrow down what is going on.

**Comment by samteb** [comment]
Hi @dougwilson !

I have checked and the `IsProduction` boolean variable is set to true.
I reconfig my AWS Cloudfront and now I have more headers coming through:

```
connection: 'upgrade'
x-forwarded-for: someIp
host: 'api.myDomain.com',
pragma: 'no-cache'
cache-control: 'no-cache'
accept: 'application/json, text/plain, */*'
origin: 'https://dashboard.com'
authorization: 'Bearer blablabla'
user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36'
sec-fetch-mode: 'cors'
sec-fetch-site: 'same-site'
referer: 'https://dashboard.com',
accept-encoding: 'gzip, deflate, br',
accept-language: 'en-US,en;q=0.9',
cookie: someCookies
```

**Comment by dougwilson** [comment]
Ah, thanks for that! Looks like you are just missing the `x-forwarded-proto` header coming from your proxy to indicate that the connection is over https.

**Comment by samteb** [comment]
I don't get any `x-forwarded-proto` header from my proxy ! Should I add it manually as a middleware to every request ?

**Comment by dougwilson** [comment]
If your express server is only ever accessed over https, you can just `Object.defineProperty(app.request, 'protocol', { value: 'https' })`

**Comment by samteb** [comment]
I have just tried what you suggested.

I do get in my headers `protocol: https` but still no session cookie in the browser.

**Comment by dougwilson** [comment]
The above code doesn't add anything to your headers. Can you share your complete code so I can debug though it?

**Comment by samteb** [comment]
I just added what you suggested as below :

```
if (isProduction) {
    app.enable('trust proxy');
    Object.defineProperty(app.request, 'protocol', { value: 'https' });
}
```

The `req.headers` give me the same with `protocol: https`

**Comment by dougwilson** [comment]
Yea, that is weird. I added that to the code that you posted above and I'm _not_ seeing a protocol: https header like you are describing and the secure cookie header is there now. I'm not sure why we are getting different results in the same app, which is why I'm trying to normalize what we both have here, hoping you can provide the full app that you are using now so I can copy and paste it and run to debug though to understand why it's not working.

**Comment by samteb** [comment]
```
const app = express();
const server = http.Server(app);
const args = commandLineArgs([ { name: 'port', alias: 'p', type: Number } ]);
const port = args.port || config.port;
const isProduction = ['production', 'staging'].includes(process.env.NODE_ENV);

if (!port) {
    throw new Error('Port should be specified!');
}

app.set('port', port);
app.use(helmet());
app.use(cors({
    credentials: true,
    origin: (origin, callback) => {
        if (!origin || origin === 'null' || [ 'localhost', 'myDomain.com' ].some(value => origin.indexOf(value) >= 0)) {
            callback(null, true)
        } else {
            console.log('not allowed by CORS', origin);
            callback(new Error('Not allowed by CORS'))
        }
    }
}));

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(bodyParser.text());

if (isProduction) {
    app.enable('trust proxy');
    Object.defineProperty(app.request, 'protocol', { value: 'https' });
}

app.use(session({
    name: 'sessionId',
    proxy: true,
    resave: false,
    saveUninitialized: false,
    secret: 'mySecret',
    store: new redisStore({ client: redisClient }),
    cookie: {
        path: '/',
        secure: true,
        httpOnly: true,
        maxAge: 1000 * 60 * 60 * 10
    },
    unset: 'destroy'
}));

server.listen(app.get('port'), () => {
    logger.log('Video recorder server listening on port ' + app.get('port'));
});

socket.init(server);

```

**Comment by samteb** [comment]
@dougwilson did you find any issue so far ?

**Comment by dougwilson** [comment]
Right when you sent that I was leaving for work, so haven't had an opportunity to check it before I left. I will try and check tonight if I have time.

**Comment by dougwilson** [comment]
Ok, so trying to run the code provided gave an error right away:
```
const app = express();
            ^

ReferenceError: express is not defined
```

So that seemed easy to fix, so I added the require for `express` at the top, then for `http`. Then there is `commandLineArgs` which is not defined, and I'm not sure how to get that defined, so I tried to removed the references to that, which made `args` undefined. I set it to `{ port: 3000 }`. Then got `helmet` undefined and so installed and added a require for that too. Same for `cors`, then `bodyParser`, then `session`. Then `redisStore` is not defined (and neither is `redisClient`) so I just removed that config from session just to get past that. Then `socket` is not defined, and not sure how to get that defined, so deleted that line. Same for `logger`.

Then the server was able to start.

I made a request to the server and there was no set-cookie, which is because there is no code to put anything into the session / create one, so I added `app.get('/', (req, res) => { req.session.foo = 12; res.send(); })`.

I wasn't getting a set-cookie header still. I realized that `isProduction` was `false` during debugging it, so set it to `const isProduction = true;`.

Ultimately, the reason why adding the `Object.defineProperty` didn't work is because you are setting `proxy: true`, which is not using the Express trust proxy settings. Just remove that from your config and it will then work, as it will use the express settings.

**Comment by samteb** [comment]
@dougwilson thanks for your answer.

Of course that all the packages were included in my file. I thought unnecessary to add all those lines above.

The `isProduction` is set to `true` and `Object.defineProperty` worked well, even with `proxy = true` because I get the headers `protocol: https`

Anyway, I don't know what is wrong and why locally it works fine.
