### ISSUE TITLE
Allow configurable key omissions on hash?

### ISSUE THREAD

**Issue by jasonroman** [expressjs/session#702]
Hello,

I am currently using express sessions with redis and flash messages.  Whenever I save a flash message to the session it modifies `req.session.flash`, which in turn modifies the session hash, so `isSaved()` returns false, and the session re-saves.  I want to ignore the 'flash' key when hashing my session, but currently sessions are hard-coded to only ignore the 'cookie' variable.

Unless there is another way to resolve this, it seems like an additional option along the lines of `hashOmitKeys` would add nice flexibility.  For example:

    var hashOmitKeys = opts.hashOmitKeys || 'cookie';

Then in the hash function, instead of:

    // ignore sess.cookie property
    if (this === sess && key === 'cookie') {
      return
    }

You could pass the omit keys to the hash function and have:

    // ignore any keys in 'hashOmitKeys' (defaults to 'cookie')
    if (this === sess && hashOmitKeys.includes(key)) {
      return
    }

This is a little unclean because the `hashOmitKeys` would have to be passed around everywhere, but there could be a cleaner solution.

**Comment by dougwilson** [comment]
So maybe I'm not understanding the purpose of the flash messages, but don't you want them saved? Otherwise how will the next page load get the flash message to display it if it doesn't save it into the session?

**Comment by dougwilson** [comment]
Besides that question, the high level answer is that if you don't want something saved to the session... don't put it in the session? Why add the data into the session if you don't actually want it to be saved into the session, I guess that is another part that is confusing for the use case to me 😂

**Comment by jasonroman** [comment]
Yeah sorry I was a little vague trying to keep it short.  The issue isn't the flash messages themselves, it's that adding them triggers the session as not saved since the hashes don't match, and it re-saves.  When the session re-saves it resets the TTL to its original value on my Redis key which I don't want.

Instead of relying on the Redis TTL to expire the session I suppose I can just set the expiration in the session itself and just check against that value on each page load.

**Comment by dougwilson** [comment]
Gotcha. Though I guess that still doesn't answer the question of if you added the key to ignore as part of the hash, then the flash message you added would never get saved, right? The hash controls the session being saved back to the store due to it being modified. If the hash doesn't change due to adding the flash, then the flash message would be lost. That is, I guess, the part I'm not sure I understand. Do you not want the flash message to be saved in the session?

**Comment by jasonroman** [comment]
Ohhhh I see what you're saying.  I only need the flash message for the next page load and then it goes away anyway, and when I tested omitting the 'flash' key it was still available to me on that subsequent page load.

I will go back and test again but I manually made the change to this library to see what would happen, and I still got the flash message and it also didn't re-save the session, which is what I wanted.  Does the session typically save at the beginning of the request or the end?

**Comment by dougwilson** [comment]
> I only need the flash message for the next page load and then it goes away anyway

Yea, that's what I thought you needed for, which is why I'm confused. In order for it to be available on the next page load, it would need to save into your store.

> Does the session typically save at the beginning of the request or the end?

Unless you are specifically calling `req.session.save` somewhere specifically, this module will, on response end, check to see if the hash is different than it was before. If it is, it will then save the session back to the store.

So in the case of the flash message, when you update `req.session.flash`, nothing happens at that time. Instead, at the end of the request, the hash value is checked, and if different, will save the session. If you were to exclude the flash data from the hash, then unless you also made _other_ modification to the session in the same request, then it would never get saved back to the store, since this module would think the session is unmodified.

I hope that makes sense.

**Comment by jasonroman** [comment]
Yes that absolutely makes sense.  I just tested it again and correct, the flash doesn't get saved.  I genuinely thought it was saving on the next page load, but I was probably focused on the TTL not updating and just assumed it was still there.

Thanks for the clarification.

**Comment by dougwilson** [comment]
It's no problem at all :)
