### ISSUE TITLE
Cookie expiration date not being set correctly

### ISSUE THREAD

**Issue by paton** [expressjs/session#718]
I originally opened this issue in the `connect-redis` repo (https://github.com/tj/connect-redis/issues/292), and it was suggested the issue be raised upstream to `express-session`.

When `rolling` and `resave` are set to false, and when the session is modified, the `Expires` date on the `Set-Cookie` header is set to the current date + `maxAge`, which causes the age of the session cookie to live beyond the life of the original session (as determined by `maxAge`).

In other words, when rolling is disabled, the life of the cookie is being extended by `maxAge` each time the session data changes. The expected behavior (I believe) is that, even when the session data is modified, the session length should never exceed `maxAge` from the time the session was first created.

This is causing `connect-redis` to break because the cookie set by `express-session` is living beyond the length of the `maxAge` of the original session.

This is happening with the latest version of express-session and connect-redis, Node 10.16.0. Please see https://github.com/tj/connect-redis/issues/292 for a information / discussion of the issue. Sample code showing our configuration when the issue happens:

```
const session = require('express-session');
const RedisStore = require('connect-redis')(session);
const redis = require('redis');
const redisClient = redis.createClient(...);
const store = new RedisStore({ client: redisClient });

app.use(
  session({
      secret: 'secret here',
      store: store,
      resave: false,
      rolling: false,
      saveUninitialized: false,
      proxy: true,
      name: 'xyz',
      cookie: {
        maxAge: 1000 * 60 * 60 * 24 * 14,
        path: '/',
        secure: true,
        httpOnly: true,
      },
    });
);
```

**Comment by dougwilson** [comment]
> The expected behavior (I believe) is that, even when the session data is modified, the session length should never exceed maxAge from the time the session was first created.

This us not how it works. The module works like you are describing as it is intended to work that way. It just seems you are expecting to opposite of how it is designed to work is all.

> This is causing connect-redis to break because the cookie set by express-session is living beyond the length of the maxAge of the original session.

This session store should be keeping the session alive.

Remember, the values under the "cookie" section are the values the cookie takes, as specified by the RFC for cookie. The "maxAge" attributes sets the maxAge for the cookie. The only thing rolling does is set the cookie on every response instead of only on the responses where the session is modified.

I hope that helps. The behavior you are seeing is how this module has works since it was first created and is intended. If you want to see a method to set a maximum limit for the session as a whole, you're welcome to open a feature proposal for it, and maybe even a PR if you're up to it :)

**Comment by paton** [comment]
Thanks @dougwilson, looks like this is a scenario that should be fixed in `connect-redis` in that case.

**Comment by dougwilson** [comment]
I'm surprised to even hear that store has such an issue. I haven't used it in a while, but when I did I never had that problem. Not sure if there are store settings that conflict or if there is a recent regression in the module around it or something. Do previous versions have the issue?

**Comment by paton** [comment]
The issue began when upgrading `connect-redis` from `3.4.2` to `4.0.3`.

The issue starts to happen when modifying the session `maxAge` after the initial session was created. `connect-redis` attempts to save the modified session and (I'm guessing) calculated the TTL of the redis record as "currentTime - sessionCreationDate" which results in a negative TTL. Since TTL should always be positive, Redis throws `ERR invalid expire time in set`.

One thing I found particularly strange is that `console.log(req.session.cookie._expires)` will print the date the session was first created (for example, December 14th), but in the `Set-Cookie` header the actual `Expires` date is the current time the response was served (for example, December 16th). Not sure if it's expected that `req.session.cookie._expires` does not match the `Expires` date in `Set-Cookie`.

**Comment by dougwilson** [comment]
If they do not match, it is likely the store is not actually saving the updated value this module is asking it to store.

**Comment by wavded** [comment]
The TTL in Redis is set to whatever the 'session.cookie.expires` value is compared to "now", another popular library (connect-mongo) does similar.  Is it possible that the expires could be set in the past somehow?

https://github.com/tj/connect-redis/blob/master/lib/connect-redis.js#L126

**Comment by dougwilson** [comment]
It is possible. Does the same issue reproduce on our MemoryStore store included here? Or if not, is there some kind of minimum reproduction case someone can provide and the instructions for how to get everything set up to reproduce the issue? That would give us something concrete to investigate if there is a suspected issue.

**Comment by wavded** [comment]
@paton would you be able to provide a code sample to reproduce?

**Comment by paton** [comment]
@wavded Please find a small node app that reproduces the issue below.

@dougwilson Re: MemoryStore, the issue does not happen when using MemoryStore. Also noticed that when using MemoryStore, `req.session.cookie.expires` changes every time the session data is saved. But when using RedisStore, `req.session.cookie.expires` never changes after saving the session. I'm not sure which is the expected behavior with `rolling: false`.

**Needed to reproduce:**
- Node modules:  express, redis, express-session, connect-redis
- Local redis server listening on 6379
- Run the script and open http://localhost:3000

```js
'use strict';

const generateResponse = (req, message) => {
  let html = '';
  if (message) html += `<p><br /><b>Message</b><br/><code><pre>${message}</pre></code></p>`;
  html += `
    <h1>express-session issue #718 reproduction</h1>
    <h2>Reproduction steps</h2>
    <ol>
      <li>Click "<a href="/generate">Update session</a>" repeatedly. The error will appear after ~5 seconds</li>
      <li>Wait another 10 seconds (without clicking update session)</li>
      <li>Click "Update session" again, and the error is gone.</li>
      <li>To clear the session and start again: <a href="/delete">Delete Session</a></li>
    </ol>
    
    <p><b>NOTE:</b> The value of <code>req.session.cookie.expires</code> is NOT the actual cookie expiration date sent in the <code>Set-Cookie</code> header (except when the session is first created). This causes the session cookie in the browser to remain valid well beyond the <code>req.session.cookie.expires</code> date (despite rolling: false).</p>

    <p>If you use MemoryStore instead of RedisStore, the value of <code>req.session.cookie.expires</code> is updated every time the session is saved, which does not happen when using RedisStore.</p>

    <h2>Value of req.session.randomNumber</h2>
    <p>${req.session ? req.session.randomNumber : 'req.session is undefined'}</p>

    <h2>Value of req.session object</h2>
    <code><pre>${req.session ? JSON.stringify(req.session, null, 2) : req.session}</pre></code>
  `;
  return html;
};

const startServer = () => {
  const http = require('http');
  const express = require('express');
  const redis = require('redis');
  const session = require('express-session');
  const RedisStore = require('connect-redis')(session);

  const redisClient = redis.createClient({
    host: 'localhost',
    port: 6379,
  });

  const server = express();

  server.use(session({
    secret: 'xyz',
    store: new RedisStore({ client: redisClient }),
    resave: false,
    rolling: false,
    saveUninitialized: false,
    proxy: false,
    name: 'oei8',
    cookie: {
      maxAge: 1000 * 5,
      path: '/',
      secure: false,
      httpOnly: true,
    },
  }));

  server.get('/generate', (req, res) => {
    req.session.randomNumber = Math.round(Math.random() * 100000);
    req.session.save((err) => {
      if (err) {
        console.error(err);
        return res.send(generateResponse(req, err.message + '\n' + err.stack));
      }
      res.send(generateResponse(req, `<code>req.session.randomNumber</code> assigned value ${req.session.randomNumber}`));
    });
  });

  server.get('/delete', (req, res) => {
    req.session.destroy((err) => {
      if (err) throw err;
      res.send(generateResponse(req, 'Session destroyed'));
    });
  });

  server.get('/', (req, res) => {
    res.send(generateResponse(req));
  });

  // Listen to http; AWS (ELB) handles https
  http.createServer(server).listen(3000);
};

startServer();
```

![image](https://user-images.githubusercontent.com/609881/72688886-b78ce580-3ad9-11ea-99cb-8a53cc081ebc.png)

**Comment by dougwilson** [comment]
> MemoryStore, the issue does not happen when using MemoryStore. Also noticed that when using MemoryStore, req.session.cookie.expires changes every time the session data is saved. But when using RedisStore, req.session.cookie.expires never changes after saving the session. I'm not sure which is the expected behavior with rolling: false.

The expectation is that it should work like MemoryStore. The built-in MemoryStore is a reference implementation to help others make stores. The behavior you are describing and what I see in your demo is an issue with that store.

I believe this used to work in connect-redis, so there is likely a regression in this module, as there has not been a change around that in this module to my knowledge.

**Comment by dougwilson** [comment]
From what I can tell testing with your example and looking at the connect-redis module, it seems connect-redis never really saved the cookie expiration date to their store. This just "happened" to not cause a visible issue until in the 4.0 release they actually started to try and use that value. Since the connect-redis module isn't storing the updates to that value, it will keep handing back to express-session an old value for that, and eventually that value turns from the future to the past and it seems like then Redis doesn't like that.

If the module is going to use that date to set the TTL on keys in Redis, it would need to actually store the value as well if it doesn't expect the value to go from the future into the past... right? There is no other method this module can store the new updated value outside from the store in use.

**Comment by wavded** [comment]
@dougwilson I guess I'm not totally tracking. In v3, we used `maxAge` to determine TTLs, and we switched to `expires` in v4, like `connect-mongo` does. I guess I'm not sure how `express-session` manipulates that value, I was under the assumption that it was updating the value after it receives it from the store, or perhaps getting data directly from the cookie. We do store the updated value on any `set` call, but not for `touch`, do we need to do it there as well?

Or does the behavior change when a client sets a `maxAge` explicitly like in the example above?

**Comment by dougwilson** [comment]
Yes, this module will reset the cookie expires right before setting the cookie, but since in the example req.session.save is being called manually prior to the cookie set, it will be called with the data that came from the session store. At that point, the cookie in the browser has not been modified and there is no guarantee it will be if it is destroyed before the response ends.

**Comment by wavded** [comment]
Ok, so to reiterate how I understand your comment. Manual `session.save` calls won't have the updated cookie.expires information because they are called before the middleware has a chance to update the cookie value.

If this is correct, it seems to introduce a behavior difference when using the `save` manually instead of it saving automatically. I would imagine this issue exists in other stores like `connect-mongo`. I personally don't manually save so I haven't ever encountered it.

Should the cookie be updated at the start of the request instead such that any manual saves match the automatic save behavior?

**Comment by dougwilson** [comment]
The issue is if it is updated at the start, then there isn't a chance for users to write code to make decisions on when the cookie expires, as it would always look like maxAge inside the user route code.

**Comment by wavded** [comment]
Is there a way for manual saves to know what the expiration "would be" on a manual save without changing the original value? Just trying to think of ways to avoid having the stores figure this out and thus having different implementations. One of the big reasons we switched to expires was to completely depend on express-session to tell us how our TTLs should be set, we had a variety of weird edge cases before.

**Comment by dougwilson** [comment]
So a manual save can occur at any time, even apart from the original request. So at the time of the manual save, it may still be another minute of processing before the response is sent, or it could be in a websocket in which no further response will ever be sent. There is definitely a lot of edge cases all around, which is why the current implementation tried to at least be somewhat predictable: the expiration is what was loaded from the store and only changes when (or even if) the cookie is actually set on the response.

**Comment by wavded** [comment]
Gotcha, so seems the responsibility should be on the implementer of the application using the store if they choose to save manually. It seems I'd have the same problems as you if I implemented something "smart" in the store and it sure wouldn't be consistent with other stores! Thx

**Comment by dougwilson** [comment]
Well, I mean, my guess would be that the store would (at least by default) simply set the data expiration time to `currentDate + maxAge` whenever there is a `.save()` or a `.touch()`, with the `.touch()` being a signal that only the expiration should be updated (if the store desires to do so). That should be just a TTL set on the existing key for Redis, I would guess. It is possible to set up some method where both the cookie and the session could share the exact same expiration, but I'm not sure if that's truly desired in the long run. The biggest downside is that the store needs to "peek" into the session data in order to just work... but yes, there is no way for the store to otherwise know what the user configured the `maxAge` to in this module, so I think maybe that's where this pattern came from.

Really, some of the interface between the store and this module ("manager"?) does need to be overhauled for a 2.x. I believe there is already a request out there such that this module could inform the store of what settings were used for reference (things like `maxAge`), but it needs some more though in what the interface would look like when the same store is supplied to more than one "manager" with different TTLs (perhaps an anonymous section vs a logged in section, idk).
