### ISSUE TITLE
Not able to override current connect.sid with samesite: none without losing session

### ISSUE THREAD

**Issue by jaisonka91** [expressjs/session#735]
### **currently, I have connect.sid with no samesite value, want to override it with samesite as none without losing the session.** 

```
let cookieObj = {
    maxAge: 180000,
    expires: new Date(new Date().getTime()+180000),
    secure: true
}

app.use(session({
    cookie: cookieObj,
    secret: 'abcdefght',
    resave: true,
    rolling: true,
    saveUninitialized: true,
    store: new redisStore({client: client}) // redis client
}));
```

**this is my current session manager, in cookieObj i have added samesite now,**

```
let cookieObj = {
    maxAge: 180000,
    expires: new Date(new Date().getTime()+180000),
    secure: true,
    sameSite: "none"
}

```
**this is not updating the current cookie, for new sessions it is working properly.**
_I tried updating cookie by res.cookie() new object from * route, its updating the cookie but after redirecting from payment page session is getting remove._ 

Help me to update the current cookie without losing session
#

**Comment by ghinks** [comment]
thank you @jaisonka91 just a couple of notes from the readme.md page 

```If both expires and maxAge are set in the options, then the last one defined in the object is what is used.```

I will try the cookie configuration you have set and get back to you shortly.

**Comment by jaisonka91** [comment]
@ghinks Currently in my app I'm not setting samesite value in the cookie, it was working fine till the last chrome update, after the last chrome update what is happening is when the user reaches payment page, if he is not able to finish the transaction in 2mins while redirecting back to our app session is getting destroyed. I found that if we set samesite value as none we can resolve this issue. And I have done that. But for the current users, the cookie doesn't have samesite value.
What i want is to update the cookie real time. for that i tried adding 


```
let cookieObj = {
    maxAge: 180000,
    expires: new Date(new Date().getTime()+180000),
    secure: true,
    sameSite: "none"
}

app.use('*', (req, res) => {
    res.cookie('connect.sid', req.cookies["connect.sid"], cookieObj);
    res.send(`<>SAMPLE SAMPLE</>`);
});
```

its updating cookie,  but for current users for the first time it will fail and session is getting destroyed. so i think its not a proper way to update the cookie. Is there any way to do that?

**Comment by ghinks** [comment]
OK, thank you for clarification. 
So in summary due to a change in chrome's handling of sameSite cookie parameter on the client, when you change the sameSite to "none" you have a fix for new users. However pre-existing users who are already cookied without sameSite being explicitly set now have issues

There does appear to have be a change in [chrome](https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html) and I am looking into this now.

**Comment by ghinks** [comment]
**I have looked into how the chrome 80 change would impact you**

For pre-existing users that default to the sameSite lax it looks like the cookie will not be sent to your third party. This would result in the symptoms you describe. This is not a common change you are encountering and I do not expect you to have to do so again. Alas it does look like the sameSite setting will remain unset until a new cookie is dropped and you loose session.

**Comment by dougwilson** [comment]
The unfortunate part is that it is too late to fix your existing sessions, AFAIK. Because all those cookies that were from before users who upgraded to Chrome 80 won't have the change, and so Chrome will not send them back to the server here for this module to even "fix" them after the fact... if Chrome does not send the cookie, this module doesn't know the session ID in order to provide an updated cookie.
