### ISSUE TITLE
How to use express-session in unit testing

### ISSUE THREAD

**Issue by ryanroundhouse** [expressjs/session#773]
I implemented an express API which uses express-session to attach a userId to a request when someone hits the '/login' endpoint.
If someone hits '/login' when they already have a req.session.userId, it returns a 400 series error.
I can't figure out how to mock out a session already being attached to the request in one of my tests.

Do you have any samples of how to accomplish this in a unit test?

**Comment by ghinks** [comment]
I understand the question @ryanroundhouse but this is an application question and not specifically an express-session question. May I suggest that in the express-session unit tests there are a number of examples where we pre-populate session so that it has values that may be checked. You may check in the createServer method calls and see that we are pre-populating req.session. These are mocha based unit tests. What you are asking is that a unit test sees that an expected session property already exists and makes a response based upon that. ( lots of examples in the repo )

**Comment by ryanroundhouse** [comment]
Thanks for referring me to the examples in the repo.  This helped a lot.
