### ISSUE TITLE
VSCode not loading merged declaration

### ISSUE THREAD

**Issue by tbhaxor** [expressjs/session#792]
After upgrading typescript and express-session, the tsc is loading custom type defination stubs.

[![enter image description here][1]][1]

I am getting this error even though i have merged type declaration here

[![enter image description here][2]][2]

Also i have added `./typing-stubs` in tsconfig.json
```json
"typeRoots": [
      "./typing-stubs",
      "./node_modules/@types"
],
```

The problem is, type merging for `express` is loading but not for `express-session`

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/T7fnu.png
  [2]: https://i.stack.imgur.com/PJEUd.png
  [3]: https://i.stack.imgur.com/C5Fs1.png

**Comment by bencevans** [comment]
Hopefully of some help. I've just sorted it here with:

```ts
declare module "express-session" {
  interface Session {
    user: string;
  }
}
```

The interface decalred for `req.session` seems to have changed from `SessionData` to `Session` from `@types/express-session` 1.17.0 → 1.17.1.

This issue is probably more at home over at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express-session where the `@types/*` modules live.

**Comment by tbhaxor** [comment]
Thanks a lot @bencevans you saved my day

**Comment by tbhaxor** [comment]
> `req.session` seems to have changed from `SessionData` to `Session`

@bencevans Then why did clicking on `session` in `req.session` I was redirected to SessionData typing stub?
