### ISSUE TITLE
attach a property to session, but not found in anohter route

### ISSUE THREAD

**Issue by sqllyw** [expressjs/session#814]
Hi,

I have a simple demo here:

https://jsfiddle.net/1vt38Loj/

basically I do:

     req.session.loggedIn = true;

and in another route, i do:

    console.log(req.session.loggedIn);

it is underfined, why? Thanks

**Comment by dougwilson** [comment]
Hi @sqllyw I'm not sure how to get your fiddle to run, and it keeps saying that `require` is not there. Because your code is altering the session and then immediately performing a redirect, the session may not be fully saved before the new page is loaded. You may want to manually save before redirecting: https://github.com/expressjs/session#sessionsavecallback
```js
app.get('/login', (req, res) => {
    req.session.loggedIn = true;
    console.log(req.session.loggedIn)  // show true
    req.session.save(() => res.redirect("/"));

})
```

**Comment by sqllyw** [comment]
thanks, turn out the its here:

  cookie: { secure: false }

and it has been documented:

https://github.com/expressjs/session#cookiesecure

here is the running code:

https://runkit.com/embed/q7x9ht59wztq
