### ISSUE TITLE
Session  regenerate doesn't send updated session cookie to the browser

### ISSUE THREAD

**Issue by amcinfo** [expressjs/session#828]
In the following code, I expect the session cookie to be changed on every other page refresh, however the session cookie doesn't change when req.session.regenerate is invoked, as a result the new session ID created by regenerate is ignored. Effectively this means that the regenerated session data is not kept and regenerate works the same as destroy session.

```js
var express = require('express');
var session = require('express-session')

var app = express()

app.use(session({ secret: 'keyboard cat', cookie: { maxAge: 60000 }}))

app.get("/", function(req, res) {

    if (req.session.a == 1) {
        req.session.a = 0
    } else {
        req.session.a = 1
    }

    res.write('<p>Previous session ID: ' + req.session.id + '</p>')

    if (req.session.a == 0) {
        req.session.regenerate(function(err) {
            res.end('<p>New session ID: ' + req.session.id + '</p>')
        })
    } else {
        res.end('<p>Session is not regenerated on this page load</p>')
    }
})

app.listen(3001);
```

**Comment by dougwilson** [comment]
Hello @amcinfo and thank you so much for your app above. I debugged it a little and the issue is that you are calling `res.write` before you call `req.session.regernate`. Because `res.write` will write out data to the response, the response headers are also generated at that time, which includes the `set-cookie` header. Unfortunately once the http response headers are written out, you cannot change them.

The solution would be to store the first write in a variable and write the entire response at the end, so the new session ID can be included in the response headers. Here is an example app:
```
var express = require('express');
var session = require('express-session')

var app = express()

app.use(session({ secret: 'keyboard cat', cookie: { maxAge: 60000 }}))

app.get("/", function(req, res) {

    if (req.session.a == 1) {
        req.session.a = 0
    } else {
        req.session.a = 1
    }

    var body = '<p>Previous session ID: ' + req.session.id + '</p>'

    if (req.session.a == 0) {
        req.session.regenerate(function(err) {
            res.end(body + '<p>New session ID: ' + req.session.id + '</p>')
        })
    } else {
        res.end(body + '<p>Session is not regenerated on this page load</p>')
    }
})

app.listen(3001);
```

**Comment by amcinfo** [comment]
Thanks @dougwilson, it works perfectly as you've described.
