### ISSUE TITLE
Enhanced security properties

### ISSUE THREAD

**Issue by 0x0ece** [expressjs/session#830]
Hi, we publish a fork [express-session-jwt](https://www.npmjs.com/package/express-session-jwt) that uses JWT as session tokens and enhance some security properties (see [blog post](https://hackernoon.com/secure-sessions-in-javascript-forking-express-session-to-improve-security-s62c35mk) for more details).

The use of JWT is clearly a major change so let's leave it aside. I'd like to discuss 3 other security enhancement that I think could be merged back into express-session. I'd be happy to contribute a PR, but I'd like to get your opinion/approval first.

1. Store `hash(sessId)` instead of `sessId`. The advantage is that access to the data store (plus the symmetric key) allows to reconstruct all active sessions. With this change, this would no longer be possible. This is a relatively small change, and (like we did in our fork, you could support a transparent upgrade).

2. Better interface for stores, with explicit insert+update vs generic set. This would prevent a race condition on logout where a slow request that updates the session can overwrite a logout, making the session alive again. With SQL-like stores it's relatively easy to prevent the race condition with a soft delete (see discussion on [connect-typeorm](https://github.com/nykula/connect-typeorm/issues/25)). With non-SQL stores this is harder, but would be easy if express-session supported explicit insert+update operations. See the discussion on [connect-redis](https://github.com/tj/connect-redis/issues/328).
 
3. Public key crypto vs symmetric. This would reduce the presence of the key on potentially many systems. One nice extra feature would be using express-session in read-only mode (with just the public key), so you could have systems that can verify a session, but centralize the issuing. Public key crypto itself could be a relatively small change, the distinction read-only vs read+write a medium one.

Please lmk your thoughts on 1), 2) and 3). For 2), given the discussion, we can probably onboard connect-redis to prove the new interface.

**Comment by dougwilson** [comment]
Thanks for opening this. Can yoi split each of these into individual issues? Having them all in one issue ends up muddying the comment lines and there will be parallel discussions all within a single issue.

**Comment by dougwilson** [comment]
In addition, please ensure that if you are reporting any actual security issues you reach out regarding those outside of public channels. If you don't think there is a security issue, please make rhat very clear in the issue, as many times third party security companies will see an issue that states security and then suddenly files CVEs on the project without discussion since it was a public post.

**Comment by dougwilson** [comment]
In the interest in not exposing our users to a protentional issue, since I haven't heard back regarding if any of these are actually security issues or not, I am going to lean on the safe side and remove the original report so we can analyze them privately without the post remaining public for some unknown amount of time. If any of these are actual security issues, please reach out privately so you can take part on the conversation to address them. Any that are not, please feel free to re-post them (but please, make a new issue for each issue listed) and if you could add some wording in there that it doesn't present any security issue to users of this module if unresolved (otherwise it should be reported privately, at least first so we have an opportunity to address and release a fix without a public disclosure and a very rushed out fix). Thanks again and I look forward to hearing back.
