### ISSUE TITLE
Link the session with a model

### ISSUE THREAD

**Issue by yahiarefaiea** [expressjs/session#847]
This is more like a question,
I have a session with MongoStore (connect-mongo) that's working well.

In addition to the auto-generated collection for sessions, I have another one called "tests".

Let's say I want to generate a test for each new session and link the test ID with the session; so I can update the test until the user completes it. (and then deletes the test ID so the user can start another)

I have one easy option, which is:
```
testModel.save(function(err) {
  req.session.test_id = testModel._id
})
```

Or, a second option, as we usually link models together, we use the `type`, `ref` attributes. Like:
```
const sessionSchema = Schema({
  ...
  test: { type: Schema.Types.ObjectId, ref: 'Session' },
  ...
});
```

My question is, what's the best practice to link other models with the session model?
The second option is a bit confusing since I couldn't find a way to update the session schema.
But the first option seems like the best practice.. Still, I don't like to just throw the ID like this.
That's why I called for your help guys.
What can I do here?

**Comment by dougwilson** [comment]
Hello, and thanks for the question. If you are using a store that integrates with the same database you are using for the rest of the data, you would need to ask on that store's issue tracker to understand how to link them directly.

But I will answer it generically, which would assume your store is completely disconnected from your data store with tests. The best practice in that case is to use a generic string column to store the session ID in your database, since that would be all you have. You could also create a middleware that checks if the session has a certain property (perhaps `req.session.dbId`) and if not, creates a new record in your data storage system and sets that to the ID of that object, and then you can use that to link everything together.
