### ISSUE TITLE
About cookie

### ISSUE THREAD

**Issue by JiaJiaJiang** [expressjs/session#852]
Hi, I have some problems with this module these days. I also found a related issue #688, after reading the code I have some advice here:
* When `rolling` and `resave` off, just do an `expires` renew without changing session value won't trigger cookie and store update. May `isModified` method take `cookie.expire` as a condition, so the cookie and session can be updated by just changing the `maxAge` or `expires` value without any changing on session value. 
* I found that the `shouldSetCookie` method use session's `isModified` method as a condition, can we replace it by `isCookieModified` method so the cookie won't be set if there's nothing changed on cookie.
* Auto `touch()` at the end of the response confused me 2 days until I read the code, what about add an option to disable this feature because someone like me don't want to renew cookie time by `originalMaxAge` after changing session value. (I just deleted related code in my fork to solve the problem, but I think its not a good solution, so it becomes an issue here)

**Comment by dougwilson** [comment]
Hello, please post your response in the original iasue rather than opening a new issue about the same thing so we can keep everything together. For example, there may be someone who would like to contribute about the original issue, but they are only subscribed to updates in that thread, so won't see your response since this was a new issue.

**Comment by JiaJiaJiang** [comment]
OK
