### ISSUE TITLE
req.session.destroy with res.redirect : session is not destroyed

### ISSUE THREAD

**Issue by devniel** [expressjs/session#93]
If I do a redirection after destroying  a session, it's not deleted. If in the redirected page I do a request, maybe a refresh, the req.session object is now empty. I solve my problem using `regenerate` instead of `destroy`.

**Comment by episodeyang** [comment]
Why do we have to redirect afterward? I noticed that the response has a 302 status code in it and a new session is created.

**Comment by dougwilson** [comment]
> Why do we have to redirect afterward?

You don't... the original question was literally how to redirect, so of course the answer was showing how to do a redirect. If you are having an issue or have a question, please open a new issue, rather than commenting on an old one (you can always put a link in your new issue to an old issue if you think it's relevant).
