### ISSUE TITLE
index.js - line 342 - why is it calling the 'createSession()' function on store?

### ISSUE THREAD

**Issue by iddogino** [expressjs/session#97]
I am implementing a custom session store (on Mongo), and I was getting an error about a `createSession()` function not being implemented. I further investigated and found out that this method was not implemented by the `MemoryStore` as well, but that it was implemented in the `/session/store.js` file. 

Is that a mistake?

Why not just put `req.session = new Session(req, sess);` there instead? It makes much more sense...

**Comment by dresende** [comment]
The documentation (Readme) does not explain correctly in my opinion. It should not say the store must extend from an `EventEmitter` but from the `require("express-session").Store`. This way you only need to implement the methods as described in the docs (`get`, `set` and `destroy`). Otherwise `createSession` is needed (which means you need to create `resetMaxAge`, `touch`, `save`, ... on `req.session`).

**Comment by dougwilson** [comment]
Thanks for the feedback, @dresende . Saying "the store must extend [...] from the require("express-session").Store" would be a complete lie, but we could update the documentation to say that you _could_ do this, if you wait, but if you do, your module _cannot depend on express-session_, rather it needs to take it in as an argument, which is what `connect-redis` does.

**Comment by dresende** [comment]
Yes, something should be changed to have a more clean documentation about making your own store. For me the dependency is not a problem because I'm using the module so I already depend on it. But yeah, that applies to people making modules like `connect-redis`.

**Comment by dwhieb** [comment]
For all practical purposes, the Store implementation does need to extend from store.js of express-session. This is because store.js itself depends on both session.js and cookie.js. So implementing one's own version of the methods in store.js also means reimplementing (or simply copying) session,js and cookie.js. The result is that a Store implementation either includes most of express-session's .js files (or some reimplementation thereof), or it must extend from store.js.

**Comment by caub** [comment]
But `store#createSession` is not listed in Readme, it's rather `store#set` that plays this role https://github.com/expressjs/session#storesetsid-session-callback

**Comment by chr15m** [comment]
I ran into this same issue. As per the documentation, I created a session store which inherited from `EventEmitter`. An error was thrown when `createSession` was missing. When I instead inherited from `require("express-session").Store` the error was not thrown. Should the documentation be updated to say that `createSession` should either be implemented or inherited from? There is no mention of this function in the documentation.
